// Code generated by ent, DO NOT EDIT.

package longtaskprogress

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the longtaskprogress type in the database.
	Label = "long_task_progress"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLongTaskID holds the string denoting the long_task_id field in the database.
	FieldLongTaskID = "long_task_id"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldTotal holds the string denoting the total field in the database.
	FieldTotal = "total"
	// FieldUnits holds the string denoting the units field in the database.
	FieldUnits = "units"
	// EdgeLongTask holds the string denoting the long_task edge name in mutations.
	EdgeLongTask = "long_task"
	// EdgeProgressSubmissions holds the string denoting the progress_submissions edge name in mutations.
	EdgeProgressSubmissions = "progress_submissions"
	// Table holds the table name of the longtaskprogress in the database.
	Table = "long_task_progresses"
	// LongTaskTable is the table that holds the long_task relation/edge.
	LongTaskTable = "long_task_progresses"
	// LongTaskInverseTable is the table name for the LongTask entity.
	// It exists in this package in order to avoid circular dependency with the "longtask" package.
	LongTaskInverseTable = "long_tasks"
	// LongTaskColumn is the table column denoting the long_task relation/edge.
	LongTaskColumn = "long_task_id"
	// ProgressSubmissionsTable is the table that holds the progress_submissions relation/edge.
	ProgressSubmissionsTable = "long_task_progress_submissions"
	// ProgressSubmissionsInverseTable is the table name for the LongTaskProgressSubmission entity.
	// It exists in this package in order to avoid circular dependency with the "longtaskprogresssubmission" package.
	ProgressSubmissionsInverseTable = "long_task_progress_submissions"
	// ProgressSubmissionsColumn is the table column denoting the progress_submissions relation/edge.
	ProgressSubmissionsColumn = "long_task_progress_id"
)

// Columns holds all SQL columns for longtaskprogress fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldLongTaskID,
	FieldValue,
	FieldTotal,
	FieldUnits,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// LongTaskIDValidator is a validator for the "long_task_id" field. It is called by the builders before save.
	LongTaskIDValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the LongTaskProgress queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLongTaskID orders the results by the long_task_id field.
func ByLongTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongTaskID, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByTotal orders the results by the total field.
func ByTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotal, opts...).ToFunc()
}

// ByUnits orders the results by the units field.
func ByUnits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnits, opts...).ToFunc()
}

// ByLongTaskField orders the results by long_task field.
func ByLongTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLongTaskStep(), sql.OrderByField(field, opts...))
	}
}

// ByProgressSubmissionsCount orders the results by progress_submissions count.
func ByProgressSubmissionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProgressSubmissionsStep(), opts...)
	}
}

// ByProgressSubmissions orders the results by progress_submissions terms.
func ByProgressSubmissions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProgressSubmissionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLongTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LongTaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LongTaskTable, LongTaskColumn),
	)
}
func newProgressSubmissionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProgressSubmissionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProgressSubmissionsTable, ProgressSubmissionsColumn),
	)
}
