// Code generated by ent, DO NOT EDIT.

package task

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldDone holds the string denoting the done field in the database.
	FieldDone = "done"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldProblems holds the string denoting the problems field in the database.
	FieldProblems = "problems"
	// FieldQuestions holds the string denoting the questions field in the database.
	FieldQuestions = "questions"
	// FieldActions holds the string denoting the actions field in the database.
	FieldActions = "actions"
	// FieldDefinitions holds the string denoting the definitions field in the database.
	FieldDefinitions = "definitions"
	// FieldKnowledgeBits holds the string denoting the knowledge_bits field in the database.
	FieldKnowledgeBits = "knowledge_bits"
	// FieldParentContainers holds the string denoting the parent_containers field in the database.
	FieldParentContainers = "parent_containers"
	// FieldKnowledgeNodes holds the string denoting the knowledge_nodes field in the database.
	FieldKnowledgeNodes = "knowledge_nodes"
	// FieldDoneDateTime holds the string denoting the done_date_time field in the database.
	FieldDoneDateTime = "done_date_time"
	// EdgeChildrenRelations holds the string denoting the children_relations edge name in mutations.
	EdgeChildrenRelations = "children_relations"
	// EdgeParentsRelations holds the string denoting the parents_relations edge name in mutations.
	EdgeParentsRelations = "parents_relations"
	// Table holds the table name of the task in the database.
	Table = "tasks"
	// ChildrenRelationsTable is the table that holds the children_relations relation/edge.
	ChildrenRelationsTable = "container_children"
	// ChildrenRelationsInverseTable is the table name for the ContainerChild entity.
	// It exists in this package in order to avoid circular dependency with the "containerchild" package.
	ChildrenRelationsInverseTable = "container_children"
	// ChildrenRelationsColumn is the table column denoting the children_relations relation/edge.
	ChildrenRelationsColumn = "parent_id"
	// ParentsRelationsTable is the table that holds the parents_relations relation/edge.
	ParentsRelationsTable = "container_children"
	// ParentsRelationsInverseTable is the table name for the ContainerChild entity.
	// It exists in this package in order to avoid circular dependency with the "containerchild" package.
	ParentsRelationsInverseTable = "container_children"
	// ParentsRelationsColumn is the table column denoting the parents_relations relation/edge.
	ParentsRelationsColumn = "child_id"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldDescription,
	FieldTags,
	FieldDone,
	FieldNotes,
	FieldProblems,
	FieldQuestions,
	FieldActions,
	FieldDefinitions,
	FieldKnowledgeBits,
	FieldParentContainers,
	FieldKnowledgeNodes,
	FieldDoneDateTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultDone holds the default value on creation for the "done" field.
	DefaultDone bool
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultProblems holds the default value on creation for the "problems" field.
	DefaultProblems []int
	// DefaultQuestions holds the default value on creation for the "questions" field.
	DefaultQuestions []int
	// DefaultActions holds the default value on creation for the "actions" field.
	DefaultActions []int
	// DefaultDefinitions holds the default value on creation for the "definitions" field.
	DefaultDefinitions []int
	// DefaultKnowledgeBits holds the default value on creation for the "knowledge_bits" field.
	DefaultKnowledgeBits []int
	// DefaultParentContainers holds the default value on creation for the "parent_containers" field.
	DefaultParentContainers [][]interface{}
	// DefaultKnowledgeNodes holds the default value on creation for the "knowledge_nodes" field.
	DefaultKnowledgeNodes []int
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Task queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByDone orders the results by the done field.
func ByDone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDone, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByDoneDateTime orders the results by the done_date_time field.
func ByDoneDateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDoneDateTime, opts...).ToFunc()
}

// ByChildrenRelationsCount orders the results by children_relations count.
func ByChildrenRelationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChildrenRelationsStep(), opts...)
	}
}

// ByChildrenRelations orders the results by children_relations terms.
func ByChildrenRelations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildrenRelationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByParentsRelationsCount orders the results by parents_relations count.
func ByParentsRelationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newParentsRelationsStep(), opts...)
	}
}

// ByParentsRelations orders the results by parents_relations terms.
func ByParentsRelations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentsRelationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newChildrenRelationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChildrenRelationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ChildrenRelationsTable, ChildrenRelationsColumn),
	)
}
func newParentsRelationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParentsRelationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ParentsRelationsTable, ParentsRelationsColumn),
	)
}
