// Code generated by ent, DO NOT EDIT.

package repetitivetaskexecution

import (
	"arturgudiev/dashboard/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldLTE(FieldID, id))
}

// RepetitiveTaskID applies equality check predicate on the "repetitive_task_id" field. It's identical to RepetitiveTaskIDEQ.
func RepetitiveTaskID(v int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldEQ(FieldRepetitiveTaskID, v))
}

// ExecutionDate applies equality check predicate on the "execution_date" field. It's identical to ExecutionDateEQ.
func ExecutionDate(v time.Time) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldEQ(FieldExecutionDate, v))
}

// Comments applies equality check predicate on the "comments" field. It's identical to CommentsEQ.
func Comments(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldEQ(FieldComments, v))
}

// RepetitiveTaskIDEQ applies the EQ predicate on the "repetitive_task_id" field.
func RepetitiveTaskIDEQ(v int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldEQ(FieldRepetitiveTaskID, v))
}

// RepetitiveTaskIDNEQ applies the NEQ predicate on the "repetitive_task_id" field.
func RepetitiveTaskIDNEQ(v int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldNEQ(FieldRepetitiveTaskID, v))
}

// RepetitiveTaskIDIn applies the In predicate on the "repetitive_task_id" field.
func RepetitiveTaskIDIn(vs ...int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldIn(FieldRepetitiveTaskID, vs...))
}

// RepetitiveTaskIDNotIn applies the NotIn predicate on the "repetitive_task_id" field.
func RepetitiveTaskIDNotIn(vs ...int) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldNotIn(FieldRepetitiveTaskID, vs...))
}

// ExecutionDateEQ applies the EQ predicate on the "execution_date" field.
func ExecutionDateEQ(v time.Time) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldEQ(FieldExecutionDate, v))
}

// ExecutionDateNEQ applies the NEQ predicate on the "execution_date" field.
func ExecutionDateNEQ(v time.Time) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldNEQ(FieldExecutionDate, v))
}

// ExecutionDateIn applies the In predicate on the "execution_date" field.
func ExecutionDateIn(vs ...time.Time) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldIn(FieldExecutionDate, vs...))
}

// ExecutionDateNotIn applies the NotIn predicate on the "execution_date" field.
func ExecutionDateNotIn(vs ...time.Time) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldNotIn(FieldExecutionDate, vs...))
}

// ExecutionDateGT applies the GT predicate on the "execution_date" field.
func ExecutionDateGT(v time.Time) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldGT(FieldExecutionDate, v))
}

// ExecutionDateGTE applies the GTE predicate on the "execution_date" field.
func ExecutionDateGTE(v time.Time) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldGTE(FieldExecutionDate, v))
}

// ExecutionDateLT applies the LT predicate on the "execution_date" field.
func ExecutionDateLT(v time.Time) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldLT(FieldExecutionDate, v))
}

// ExecutionDateLTE applies the LTE predicate on the "execution_date" field.
func ExecutionDateLTE(v time.Time) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldLTE(FieldExecutionDate, v))
}

// CommentsEQ applies the EQ predicate on the "comments" field.
func CommentsEQ(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldEQ(FieldComments, v))
}

// CommentsNEQ applies the NEQ predicate on the "comments" field.
func CommentsNEQ(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldNEQ(FieldComments, v))
}

// CommentsIn applies the In predicate on the "comments" field.
func CommentsIn(vs ...string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldIn(FieldComments, vs...))
}

// CommentsNotIn applies the NotIn predicate on the "comments" field.
func CommentsNotIn(vs ...string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldNotIn(FieldComments, vs...))
}

// CommentsGT applies the GT predicate on the "comments" field.
func CommentsGT(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldGT(FieldComments, v))
}

// CommentsGTE applies the GTE predicate on the "comments" field.
func CommentsGTE(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldGTE(FieldComments, v))
}

// CommentsLT applies the LT predicate on the "comments" field.
func CommentsLT(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldLT(FieldComments, v))
}

// CommentsLTE applies the LTE predicate on the "comments" field.
func CommentsLTE(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldLTE(FieldComments, v))
}

// CommentsContains applies the Contains predicate on the "comments" field.
func CommentsContains(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldContains(FieldComments, v))
}

// CommentsHasPrefix applies the HasPrefix predicate on the "comments" field.
func CommentsHasPrefix(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldHasPrefix(FieldComments, v))
}

// CommentsHasSuffix applies the HasSuffix predicate on the "comments" field.
func CommentsHasSuffix(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldHasSuffix(FieldComments, v))
}

// CommentsIsNil applies the IsNil predicate on the "comments" field.
func CommentsIsNil() predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldIsNull(FieldComments))
}

// CommentsNotNil applies the NotNil predicate on the "comments" field.
func CommentsNotNil() predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldNotNull(FieldComments))
}

// CommentsEqualFold applies the EqualFold predicate on the "comments" field.
func CommentsEqualFold(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldEqualFold(FieldComments, v))
}

// CommentsContainsFold applies the ContainsFold predicate on the "comments" field.
func CommentsContainsFold(v string) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.FieldContainsFold(FieldComments, v))
}

// HasRepetitiveTask applies the HasEdge predicate on the "repetitive_task" edge.
func HasRepetitiveTask() predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RepetitiveTaskTable, RepetitiveTaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRepetitiveTaskWith applies the HasEdge predicate on the "repetitive_task" edge with a given conditions (other predicates).
func HasRepetitiveTaskWith(preds ...predicate.RepetitiveTask) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(func(s *sql.Selector) {
		step := newRepetitiveTaskStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RepetitiveTaskExecution) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RepetitiveTaskExecution) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RepetitiveTaskExecution) predicate.RepetitiveTaskExecution {
	return predicate.RepetitiveTaskExecution(sql.NotPredicates(p))
}
