// Code generated by ent, DO NOT EDIT.

package staterequirement

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the staterequirement type in the database.
	Label = "state_requirement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStateID holds the string denoting the state_id field in the database.
	FieldStateID = "state_id"
	// FieldOnceInDays holds the string denoting the once_in_days field in the database.
	FieldOnceInDays = "once_in_days"
	// EdgeState holds the string denoting the state edge name in mutations.
	EdgeState = "state"
	// EdgeChecks holds the string denoting the checks edge name in mutations.
	EdgeChecks = "checks"
	// Table holds the table name of the staterequirement in the database.
	Table = "state_requirements"
	// StateTable is the table that holds the state relation/edge.
	StateTable = "state_requirements"
	// StateInverseTable is the table name for the State entity.
	// It exists in this package in order to avoid circular dependency with the "state" package.
	StateInverseTable = "states"
	// StateColumn is the table column denoting the state relation/edge.
	StateColumn = "state_id"
	// ChecksTable is the table that holds the checks relation/edge.
	ChecksTable = "state_requirement_checks"
	// ChecksInverseTable is the table name for the StateRequirementCheck entity.
	// It exists in this package in order to avoid circular dependency with the "staterequirementcheck" package.
	ChecksInverseTable = "state_requirement_checks"
	// ChecksColumn is the table column denoting the checks relation/edge.
	ChecksColumn = "state_requirement_id"
)

// Columns holds all SQL columns for staterequirement fields.
var Columns = []string{
	FieldID,
	FieldDescription,
	FieldStateID,
	FieldOnceInDays,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// StateIDValidator is a validator for the "state_id" field. It is called by the builders before save.
	StateIDValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the StateRequirement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStateID orders the results by the state_id field.
func ByStateID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateID, opts...).ToFunc()
}

// ByOnceInDays orders the results by the once_in_days field.
func ByOnceInDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOnceInDays, opts...).ToFunc()
}

// ByStateField orders the results by state field.
func ByStateField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStateStep(), sql.OrderByField(field, opts...))
	}
}

// ByChecksCount orders the results by checks count.
func ByChecksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChecksStep(), opts...)
	}
}

// ByChecks orders the results by checks terms.
func ByChecks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChecksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newStateStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StateInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StateTable, StateColumn),
	)
}
func newChecksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChecksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChecksTable, ChecksColumn),
	)
}
