// Code generated by ent, DO NOT EDIT.

package staterequirement

import (
	"arturgudiev/dashboard/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldLTE(FieldID, id))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldEQ(FieldDescription, v))
}

// StateID applies equality check predicate on the "state_id" field. It's identical to StateIDEQ.
func StateID(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldEQ(FieldStateID, v))
}

// OnceInDays applies equality check predicate on the "once_in_days" field. It's identical to OnceInDaysEQ.
func OnceInDays(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldEQ(FieldOnceInDays, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldContainsFold(FieldDescription, v))
}

// StateIDEQ applies the EQ predicate on the "state_id" field.
func StateIDEQ(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldEQ(FieldStateID, v))
}

// StateIDNEQ applies the NEQ predicate on the "state_id" field.
func StateIDNEQ(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldNEQ(FieldStateID, v))
}

// StateIDIn applies the In predicate on the "state_id" field.
func StateIDIn(vs ...int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldIn(FieldStateID, vs...))
}

// StateIDNotIn applies the NotIn predicate on the "state_id" field.
func StateIDNotIn(vs ...int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldNotIn(FieldStateID, vs...))
}

// OnceInDaysEQ applies the EQ predicate on the "once_in_days" field.
func OnceInDaysEQ(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldEQ(FieldOnceInDays, v))
}

// OnceInDaysNEQ applies the NEQ predicate on the "once_in_days" field.
func OnceInDaysNEQ(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldNEQ(FieldOnceInDays, v))
}

// OnceInDaysIn applies the In predicate on the "once_in_days" field.
func OnceInDaysIn(vs ...int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldIn(FieldOnceInDays, vs...))
}

// OnceInDaysNotIn applies the NotIn predicate on the "once_in_days" field.
func OnceInDaysNotIn(vs ...int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldNotIn(FieldOnceInDays, vs...))
}

// OnceInDaysGT applies the GT predicate on the "once_in_days" field.
func OnceInDaysGT(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldGT(FieldOnceInDays, v))
}

// OnceInDaysGTE applies the GTE predicate on the "once_in_days" field.
func OnceInDaysGTE(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldGTE(FieldOnceInDays, v))
}

// OnceInDaysLT applies the LT predicate on the "once_in_days" field.
func OnceInDaysLT(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldLT(FieldOnceInDays, v))
}

// OnceInDaysLTE applies the LTE predicate on the "once_in_days" field.
func OnceInDaysLTE(v int) predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldLTE(FieldOnceInDays, v))
}

// OnceInDaysIsNil applies the IsNil predicate on the "once_in_days" field.
func OnceInDaysIsNil() predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldIsNull(FieldOnceInDays))
}

// OnceInDaysNotNil applies the NotNil predicate on the "once_in_days" field.
func OnceInDaysNotNil() predicate.StateRequirement {
	return predicate.StateRequirement(sql.FieldNotNull(FieldOnceInDays))
}

// HasState applies the HasEdge predicate on the "state" edge.
func HasState() predicate.StateRequirement {
	return predicate.StateRequirement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StateTable, StateColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStateWith applies the HasEdge predicate on the "state" edge with a given conditions (other predicates).
func HasStateWith(preds ...predicate.State) predicate.StateRequirement {
	return predicate.StateRequirement(func(s *sql.Selector) {
		step := newStateStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChecks applies the HasEdge predicate on the "checks" edge.
func HasChecks() predicate.StateRequirement {
	return predicate.StateRequirement(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChecksTable, ChecksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChecksWith applies the HasEdge predicate on the "checks" edge with a given conditions (other predicates).
func HasChecksWith(preds ...predicate.StateRequirementCheck) predicate.StateRequirement {
	return predicate.StateRequirement(func(s *sql.Selector) {
		step := newChecksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StateRequirement) predicate.StateRequirement {
	return predicate.StateRequirement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StateRequirement) predicate.StateRequirement {
	return predicate.StateRequirement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StateRequirement) predicate.StateRequirement {
	return predicate.StateRequirement(sql.NotPredicates(p))
}
