// Code generated by ent, DO NOT EDIT.

package story

import (
	"arturgudiev/dashboard/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Story {
	return predicate.Story(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Story {
	return predicate.Story(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Story {
	return predicate.Story(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Story {
	return predicate.Story(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Story {
	return predicate.Story(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Story {
	return predicate.Story(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Story {
	return predicate.Story(sql.FieldLTE(FieldID, id))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldDescription, v))
}

// Closed applies equality check predicate on the "closed" field. It's identical to ClosedEQ.
func Closed(v bool) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldClosed, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldNotes, v))
}

// DoneDateTime applies equality check predicate on the "done_date_time" field. It's identical to DoneDateTimeEQ.
func DoneDateTime(v time.Time) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldDoneDateTime, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Story {
	return predicate.Story(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Story {
	return predicate.Story(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Story {
	return predicate.Story(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Story {
	return predicate.Story(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Story {
	return predicate.Story(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Story {
	return predicate.Story(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Story {
	return predicate.Story(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Story {
	return predicate.Story(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Story {
	return predicate.Story(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Story {
	return predicate.Story(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Story {
	return predicate.Story(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Story {
	return predicate.Story(sql.FieldContainsFold(FieldDescription, v))
}

// ClosedEQ applies the EQ predicate on the "closed" field.
func ClosedEQ(v bool) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldClosed, v))
}

// ClosedNEQ applies the NEQ predicate on the "closed" field.
func ClosedNEQ(v bool) predicate.Story {
	return predicate.Story(sql.FieldNEQ(FieldClosed, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.Story {
	return predicate.Story(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.Story {
	return predicate.Story(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.Story {
	return predicate.Story(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.Story {
	return predicate.Story(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.Story {
	return predicate.Story(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.Story {
	return predicate.Story(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.Story {
	return predicate.Story(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.Story {
	return predicate.Story(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.Story {
	return predicate.Story(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.Story {
	return predicate.Story(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.Story {
	return predicate.Story(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.Story {
	return predicate.Story(sql.FieldContainsFold(FieldNotes, v))
}

// DoneDateTimeEQ applies the EQ predicate on the "done_date_time" field.
func DoneDateTimeEQ(v time.Time) predicate.Story {
	return predicate.Story(sql.FieldEQ(FieldDoneDateTime, v))
}

// DoneDateTimeNEQ applies the NEQ predicate on the "done_date_time" field.
func DoneDateTimeNEQ(v time.Time) predicate.Story {
	return predicate.Story(sql.FieldNEQ(FieldDoneDateTime, v))
}

// DoneDateTimeIn applies the In predicate on the "done_date_time" field.
func DoneDateTimeIn(vs ...time.Time) predicate.Story {
	return predicate.Story(sql.FieldIn(FieldDoneDateTime, vs...))
}

// DoneDateTimeNotIn applies the NotIn predicate on the "done_date_time" field.
func DoneDateTimeNotIn(vs ...time.Time) predicate.Story {
	return predicate.Story(sql.FieldNotIn(FieldDoneDateTime, vs...))
}

// DoneDateTimeGT applies the GT predicate on the "done_date_time" field.
func DoneDateTimeGT(v time.Time) predicate.Story {
	return predicate.Story(sql.FieldGT(FieldDoneDateTime, v))
}

// DoneDateTimeGTE applies the GTE predicate on the "done_date_time" field.
func DoneDateTimeGTE(v time.Time) predicate.Story {
	return predicate.Story(sql.FieldGTE(FieldDoneDateTime, v))
}

// DoneDateTimeLT applies the LT predicate on the "done_date_time" field.
func DoneDateTimeLT(v time.Time) predicate.Story {
	return predicate.Story(sql.FieldLT(FieldDoneDateTime, v))
}

// DoneDateTimeLTE applies the LTE predicate on the "done_date_time" field.
func DoneDateTimeLTE(v time.Time) predicate.Story {
	return predicate.Story(sql.FieldLTE(FieldDoneDateTime, v))
}

// DoneDateTimeIsNil applies the IsNil predicate on the "done_date_time" field.
func DoneDateTimeIsNil() predicate.Story {
	return predicate.Story(sql.FieldIsNull(FieldDoneDateTime))
}

// DoneDateTimeNotNil applies the NotNil predicate on the "done_date_time" field.
func DoneDateTimeNotNil() predicate.Story {
	return predicate.Story(sql.FieldNotNull(FieldDoneDateTime))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Story) predicate.Story {
	return predicate.Story(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Story) predicate.Story {
	return predicate.Story(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Story) predicate.Story {
	return predicate.Story(sql.NotPredicates(p))
}
