// Code generated by ent, DO NOT EDIT.

package staterequirementcheck

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the staterequirementcheck type in the database.
	Label = "state_requirement_check"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDateTime holds the string denoting the date_time field in the database.
	FieldDateTime = "date_time"
	// FieldIsFulfilled holds the string denoting the is_fulfilled field in the database.
	FieldIsFulfilled = "is_fulfilled"
	// FieldStateRequirementID holds the string denoting the state_requirement_id field in the database.
	FieldStateRequirementID = "state_requirement_id"
	// EdgeStateRequirement holds the string denoting the state_requirement edge name in mutations.
	EdgeStateRequirement = "state_requirement"
	// Table holds the table name of the staterequirementcheck in the database.
	Table = "state_requirement_checks"
	// StateRequirementTable is the table that holds the state_requirement relation/edge.
	StateRequirementTable = "state_requirement_checks"
	// StateRequirementInverseTable is the table name for the StateRequirement entity.
	// It exists in this package in order to avoid circular dependency with the "staterequirement" package.
	StateRequirementInverseTable = "state_requirements"
	// StateRequirementColumn is the table column denoting the state_requirement relation/edge.
	StateRequirementColumn = "state_requirement_id"
)

// Columns holds all SQL columns for staterequirementcheck fields.
var Columns = []string{
	FieldID,
	FieldDateTime,
	FieldIsFulfilled,
	FieldStateRequirementID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDateTime holds the default value on creation for the "date_time" field.
	DefaultDateTime time.Time
	// DefaultIsFulfilled holds the default value on creation for the "is_fulfilled" field.
	DefaultIsFulfilled bool
	// StateRequirementIDValidator is a validator for the "state_requirement_id" field. It is called by the builders before save.
	StateRequirementIDValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the StateRequirementCheck queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDateTime orders the results by the date_time field.
func ByDateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDateTime, opts...).ToFunc()
}

// ByIsFulfilled orders the results by the is_fulfilled field.
func ByIsFulfilled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsFulfilled, opts...).ToFunc()
}

// ByStateRequirementID orders the results by the state_requirement_id field.
func ByStateRequirementID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStateRequirementID, opts...).ToFunc()
}

// ByStateRequirementField orders the results by state_requirement field.
func ByStateRequirementField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStateRequirementStep(), sql.OrderByField(field, opts...))
	}
}
func newStateRequirementStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StateRequirementInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, StateRequirementTable, StateRequirementColumn),
	)
}
