// Code generated by ent, DO NOT EDIT.

package containerchild

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the containerchild type in the database.
	Label = "container_child"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldParentType holds the string denoting the parent_type field in the database.
	FieldParentType = "parent_type"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldChildType holds the string denoting the child_type field in the database.
	FieldChildType = "child_type"
	// FieldChildID holds the string denoting the child_id field in the database.
	FieldChildID = "child_id"
	// EdgeParent holds the string denoting the parent edge name in mutations.
	EdgeParent = "parent"
	// EdgeChild holds the string denoting the child edge name in mutations.
	EdgeChild = "child"
	// Table holds the table name of the containerchild in the database.
	Table = "container_children"
	// ParentTable is the table that holds the parent relation/edge.
	ParentTable = "container_children"
	// ParentInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	ParentInverseTable = "tasks"
	// ParentColumn is the table column denoting the parent relation/edge.
	ParentColumn = "parent_id"
	// ChildTable is the table that holds the child relation/edge.
	ChildTable = "container_children"
	// ChildInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	ChildInverseTable = "tasks"
	// ChildColumn is the table column denoting the child relation/edge.
	ChildColumn = "child_id"
)

// Columns holds all SQL columns for containerchild fields.
var Columns = []string{
	FieldID,
	FieldParentType,
	FieldParentID,
	FieldChildType,
	FieldChildID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	ParentIDValidator func(int) error
	// ChildIDValidator is a validator for the "child_id" field. It is called by the builders before save.
	ChildIDValidator func(int) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// ParentType defines the type for the "parent_type" enum field.
type ParentType string

// ParentType values.
const (
	ParentTypeEpic          ParentType = "epic"
	ParentTypeStory         ParentType = "story"
	ParentTypeTask          ParentType = "task"
	ParentTypeQuestion      ParentType = "question"
	ParentTypeProblem       ParentType = "problem"
	ParentTypeKnowledgeNode ParentType = "knowledge-node"
	ParentTypeKnowledgeBit  ParentType = "knowledge-bit"
	ParentTypeDefinition    ParentType = "definition"
	ParentTypeAction        ParentType = "action"
	ParentTypeScheduledTask ParentType = "scheduled-task"
	ParentTypeState         ParentType = "state"
)

func (pt ParentType) String() string {
	return string(pt)
}

// ParentTypeValidator is a validator for the "parent_type" field enum values. It is called by the builders before save.
func ParentTypeValidator(pt ParentType) error {
	switch pt {
	case ParentTypeEpic, ParentTypeStory, ParentTypeTask, ParentTypeQuestion, ParentTypeProblem, ParentTypeKnowledgeNode, ParentTypeKnowledgeBit, ParentTypeDefinition, ParentTypeAction, ParentTypeScheduledTask, ParentTypeState:
		return nil
	default:
		return fmt.Errorf("containerchild: invalid enum value for parent_type field: %q", pt)
	}
}

// ChildType defines the type for the "child_type" enum field.
type ChildType string

// ChildType values.
const (
	ChildTypeEpic          ChildType = "epic"
	ChildTypeStory         ChildType = "story"
	ChildTypeTask          ChildType = "task"
	ChildTypeQuestion      ChildType = "question"
	ChildTypeProblem       ChildType = "problem"
	ChildTypeKnowledgeNode ChildType = "knowledge-node"
	ChildTypeKnowledgeBit  ChildType = "knowledge-bit"
	ChildTypeDefinition    ChildType = "definition"
	ChildTypeAction        ChildType = "action"
	ChildTypeScheduledTask ChildType = "scheduled-task"
	ChildTypeState         ChildType = "state"
)

func (ct ChildType) String() string {
	return string(ct)
}

// ChildTypeValidator is a validator for the "child_type" field enum values. It is called by the builders before save.
func ChildTypeValidator(ct ChildType) error {
	switch ct {
	case ChildTypeEpic, ChildTypeStory, ChildTypeTask, ChildTypeQuestion, ChildTypeProblem, ChildTypeKnowledgeNode, ChildTypeKnowledgeBit, ChildTypeDefinition, ChildTypeAction, ChildTypeScheduledTask, ChildTypeState:
		return nil
	default:
		return fmt.Errorf("containerchild: invalid enum value for child_type field: %q", ct)
	}
}

// OrderOption defines the ordering options for the ContainerChild queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByParentType orders the results by the parent_type field.
func ByParentType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentType, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// ByChildType orders the results by the child_type field.
func ByChildType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChildType, opts...).ToFunc()
}

// ByChildID orders the results by the child_id field.
func ByChildID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChildID, opts...).ToFunc()
}

// ByParentField orders the results by parent field.
func ByParentField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentStep(), sql.OrderByField(field, opts...))
	}
}

// ByChildField orders the results by child field.
func ByChildField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChildStep(), sql.OrderByField(field, opts...))
	}
}
func newParentStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParentInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ParentTable, ParentColumn),
	)
}
func newChildStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChildInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ChildTable, ChildColumn),
	)
}
