// Code generated by ent, DO NOT EDIT.

package containerchild

import (
	"arturgudiev/dashboard/ent/predicate"
	"arturgudiev/dashboard/ent/schema"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLTE(FieldID, id))
}

// ParentID applies equality check predicate on the "parent_id" field. It's identical to ParentIDEQ.
func ParentID(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldParentID, v))
}

// ChildID applies equality check predicate on the "child_id" field. It's identical to ChildIDEQ.
func ChildID(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldChildID, v))
}

// ChildOrder applies equality check predicate on the "child_order" field. It's identical to ChildOrderEQ.
func ChildOrder(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldChildOrder, v))
}

// ParentOrder applies equality check predicate on the "parent_order" field. It's identical to ParentOrderEQ.
func ParentOrder(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldParentOrder, v))
}

// ParentTypeEQ applies the EQ predicate on the "parent_type" field.
func ParentTypeEQ(v schema.ContainerType) predicate.ContainerChild {
	vc := v
	return predicate.ContainerChild(sql.FieldEQ(FieldParentType, vc))
}

// ParentTypeNEQ applies the NEQ predicate on the "parent_type" field.
func ParentTypeNEQ(v schema.ContainerType) predicate.ContainerChild {
	vc := v
	return predicate.ContainerChild(sql.FieldNEQ(FieldParentType, vc))
}

// ParentTypeIn applies the In predicate on the "parent_type" field.
func ParentTypeIn(vs ...schema.ContainerType) predicate.ContainerChild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ContainerChild(sql.FieldIn(FieldParentType, v...))
}

// ParentTypeNotIn applies the NotIn predicate on the "parent_type" field.
func ParentTypeNotIn(vs ...schema.ContainerType) predicate.ContainerChild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ContainerChild(sql.FieldNotIn(FieldParentType, v...))
}

// ParentIDEQ applies the EQ predicate on the "parent_id" field.
func ParentIDEQ(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldParentID, v))
}

// ParentIDNEQ applies the NEQ predicate on the "parent_id" field.
func ParentIDNEQ(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNEQ(FieldParentID, v))
}

// ParentIDIn applies the In predicate on the "parent_id" field.
func ParentIDIn(vs ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldIn(FieldParentID, vs...))
}

// ParentIDNotIn applies the NotIn predicate on the "parent_id" field.
func ParentIDNotIn(vs ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNotIn(FieldParentID, vs...))
}

// ParentIDGT applies the GT predicate on the "parent_id" field.
func ParentIDGT(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGT(FieldParentID, v))
}

// ParentIDGTE applies the GTE predicate on the "parent_id" field.
func ParentIDGTE(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGTE(FieldParentID, v))
}

// ParentIDLT applies the LT predicate on the "parent_id" field.
func ParentIDLT(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLT(FieldParentID, v))
}

// ParentIDLTE applies the LTE predicate on the "parent_id" field.
func ParentIDLTE(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLTE(FieldParentID, v))
}

// ChildTypeEQ applies the EQ predicate on the "child_type" field.
func ChildTypeEQ(v schema.ContainerType) predicate.ContainerChild {
	vc := v
	return predicate.ContainerChild(sql.FieldEQ(FieldChildType, vc))
}

// ChildTypeNEQ applies the NEQ predicate on the "child_type" field.
func ChildTypeNEQ(v schema.ContainerType) predicate.ContainerChild {
	vc := v
	return predicate.ContainerChild(sql.FieldNEQ(FieldChildType, vc))
}

// ChildTypeIn applies the In predicate on the "child_type" field.
func ChildTypeIn(vs ...schema.ContainerType) predicate.ContainerChild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ContainerChild(sql.FieldIn(FieldChildType, v...))
}

// ChildTypeNotIn applies the NotIn predicate on the "child_type" field.
func ChildTypeNotIn(vs ...schema.ContainerType) predicate.ContainerChild {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ContainerChild(sql.FieldNotIn(FieldChildType, v...))
}

// ChildIDEQ applies the EQ predicate on the "child_id" field.
func ChildIDEQ(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldChildID, v))
}

// ChildIDNEQ applies the NEQ predicate on the "child_id" field.
func ChildIDNEQ(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNEQ(FieldChildID, v))
}

// ChildIDIn applies the In predicate on the "child_id" field.
func ChildIDIn(vs ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldIn(FieldChildID, vs...))
}

// ChildIDNotIn applies the NotIn predicate on the "child_id" field.
func ChildIDNotIn(vs ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNotIn(FieldChildID, vs...))
}

// ChildIDGT applies the GT predicate on the "child_id" field.
func ChildIDGT(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGT(FieldChildID, v))
}

// ChildIDGTE applies the GTE predicate on the "child_id" field.
func ChildIDGTE(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGTE(FieldChildID, v))
}

// ChildIDLT applies the LT predicate on the "child_id" field.
func ChildIDLT(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLT(FieldChildID, v))
}

// ChildIDLTE applies the LTE predicate on the "child_id" field.
func ChildIDLTE(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLTE(FieldChildID, v))
}

// ChildOrderEQ applies the EQ predicate on the "child_order" field.
func ChildOrderEQ(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldChildOrder, v))
}

// ChildOrderNEQ applies the NEQ predicate on the "child_order" field.
func ChildOrderNEQ(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNEQ(FieldChildOrder, v))
}

// ChildOrderIn applies the In predicate on the "child_order" field.
func ChildOrderIn(vs ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldIn(FieldChildOrder, vs...))
}

// ChildOrderNotIn applies the NotIn predicate on the "child_order" field.
func ChildOrderNotIn(vs ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNotIn(FieldChildOrder, vs...))
}

// ChildOrderGT applies the GT predicate on the "child_order" field.
func ChildOrderGT(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGT(FieldChildOrder, v))
}

// ChildOrderGTE applies the GTE predicate on the "child_order" field.
func ChildOrderGTE(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGTE(FieldChildOrder, v))
}

// ChildOrderLT applies the LT predicate on the "child_order" field.
func ChildOrderLT(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLT(FieldChildOrder, v))
}

// ChildOrderLTE applies the LTE predicate on the "child_order" field.
func ChildOrderLTE(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLTE(FieldChildOrder, v))
}

// ParentOrderEQ applies the EQ predicate on the "parent_order" field.
func ParentOrderEQ(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldEQ(FieldParentOrder, v))
}

// ParentOrderNEQ applies the NEQ predicate on the "parent_order" field.
func ParentOrderNEQ(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNEQ(FieldParentOrder, v))
}

// ParentOrderIn applies the In predicate on the "parent_order" field.
func ParentOrderIn(vs ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldIn(FieldParentOrder, vs...))
}

// ParentOrderNotIn applies the NotIn predicate on the "parent_order" field.
func ParentOrderNotIn(vs ...int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldNotIn(FieldParentOrder, vs...))
}

// ParentOrderGT applies the GT predicate on the "parent_order" field.
func ParentOrderGT(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGT(FieldParentOrder, v))
}

// ParentOrderGTE applies the GTE predicate on the "parent_order" field.
func ParentOrderGTE(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldGTE(FieldParentOrder, v))
}

// ParentOrderLT applies the LT predicate on the "parent_order" field.
func ParentOrderLT(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLT(FieldParentOrder, v))
}

// ParentOrderLTE applies the LTE predicate on the "parent_order" field.
func ParentOrderLTE(v int) predicate.ContainerChild {
	return predicate.ContainerChild(sql.FieldLTE(FieldParentOrder, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContainerChild) predicate.ContainerChild {
	return predicate.ContainerChild(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContainerChild) predicate.ContainerChild {
	return predicate.ContainerChild(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContainerChild) predicate.ContainerChild {
	return predicate.ContainerChild(sql.NotPredicates(p))
}
