// Code generated by ent, DO NOT EDIT.

package problem

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the problem type in the database.
	Label = "problem"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldProblems holds the string denoting the problems field in the database.
	FieldProblems = "problems"
	// FieldQuestions holds the string denoting the questions field in the database.
	FieldQuestions = "questions"
	// FieldActions holds the string denoting the actions field in the database.
	FieldActions = "actions"
	// FieldDefinitions holds the string denoting the definitions field in the database.
	FieldDefinitions = "definitions"
	// FieldKnowledgeBits holds the string denoting the knowledge_bits field in the database.
	FieldKnowledgeBits = "knowledge_bits"
	// FieldParentContainers holds the string denoting the parent_containers field in the database.
	FieldParentContainers = "parent_containers"
	// FieldKnowledgeNodes holds the string denoting the knowledge_nodes field in the database.
	FieldKnowledgeNodes = "knowledge_nodes"
	// FieldDoneDateTime holds the string denoting the done_date_time field in the database.
	FieldDoneDateTime = "done_date_time"
	// FieldSolution holds the string denoting the solution field in the database.
	FieldSolution = "solution"
	// Table holds the table name of the problem in the database.
	Table = "problems"
)

// Columns holds all SQL columns for problem fields.
var Columns = []string{
	FieldID,
	FieldDescription,
	FieldTags,
	FieldNotes,
	FieldProblems,
	FieldQuestions,
	FieldActions,
	FieldDefinitions,
	FieldKnowledgeBits,
	FieldParentContainers,
	FieldKnowledgeNodes,
	FieldDoneDateTime,
	FieldSolution,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultProblems holds the default value on creation for the "problems" field.
	DefaultProblems []int
	// DefaultQuestions holds the default value on creation for the "questions" field.
	DefaultQuestions []int
	// DefaultActions holds the default value on creation for the "actions" field.
	DefaultActions []int
	// DefaultDefinitions holds the default value on creation for the "definitions" field.
	DefaultDefinitions []int
	// DefaultKnowledgeBits holds the default value on creation for the "knowledge_bits" field.
	DefaultKnowledgeBits []int
	// DefaultParentContainers holds the default value on creation for the "parent_containers" field.
	DefaultParentContainers [][]interface{}
	// DefaultKnowledgeNodes holds the default value on creation for the "knowledge_nodes" field.
	DefaultKnowledgeNodes []int
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Problem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByDoneDateTime orders the results by the done_date_time field.
func ByDoneDateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDoneDateTime, opts...).ToFunc()
}

// BySolution orders the results by the solution field.
func BySolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSolution, opts...).ToFunc()
}
