package app

import (
	"arturgudiev/dashboard/repositories"
	"context"

	"arturgudiev/dashboard/ent"
	"arturgudiev/dashboard/services"
)

// App holds all application dependencies
type App struct {
	Client                   *ent.Client
	TaskService              *services.TaskService
	RepetitiveTaskService             *services.RepetitiveTaskService
	RepetitiveTaskExecutionService    *services.RepetitiveTaskExecutionService
	LongTasksService                  *services.LongTasksService
	LongTaskSubmissionsService       *services.LongTaskSubmissionsService
	LongTaskProgressesService       *services.LongTaskProgressesService
	DirectionsService                *services.DirectionsService
	StatesService                    *services.StatesService
	StatesRepository                 *repositories.StatesRepository
	StateRequirementsRepository      *repositories.StateRequirementsRepository
	StateRequirementChecksRepository *repositories.StateRequirementChecksRepository
	DirectionSubmissionsRepository   *repositories.DirectionSubmissionsRepository
	ProblemService           *services.ProblemService
	ContainerService         *services.ContainerService
	CLIService               *services.CLIService
	TasksRepository          *services.TasksRepository
	ProblemsRepository       *services.ProblemsRepository
	QuestionsRepository      *repositories.QuestionsRepository
	QuestionsService         *services.QuestionService
	StoriesRepository        *repositories.StoriesRepository
	StoriesService           *services.StoriesService
	EpicsRepository          *repositories.EpicsRepository
	EpicsService             *services.EpicsService
	KnowledgeNodesRepository *repositories.KnowledgeNodesRepository
	KnowledgeNodesService    *services.KnowledgeNodesService
	AliasesRepository        *repositories.AliasesRepository
	AliasesService           *services.AliasesService
	ChildContainerRepository *services.ChildContainerRepository
	LogMessagesRepository              *repositories.LogMessagesRepository
	VariablesStackRepository           *repositories.VariablesStackRepository
	ContainerVariablesRepository       *repositories.ContainerVariablesRepository
	RepetitiveTasksRepository          *repositories.RepetitiveTasksRepository
	RepetitiveTaskExecutionsRepository *repositories.RepetitiveTaskExecutionsRepository
	LongTasksRepository                *repositories.LongTasksRepository
	LongTaskSubmissionsRepository     *repositories.LongTaskSubmissionsRepository
	DirectionsRepository              *repositories.DirectionsRepository
	LongTasksProgressesSubmissionsRepository *repositories.LongTasksProgressesSubmissionsRepository
	LongTasksProgressesRepository *repositories.LongTasksProgressesRepository
	UsersRepository                *repositories.UsersRepository
	RefreshTokensRepository        *repositories.RefreshTokensRepository
	FilesService                   *services.FilesService
	ctx                      context.Context // Default context for CLI operations
}

// NewApp creates a new App instance with all dependencies initialized using Wire
// This function is generated by Wire - do not edit manually
// To regenerate, run: wire gen ./app
func NewApp() (*App, error) {
	return InitializeApp()
}

// Close closes all resources
func (a *App) Close() error {
	return a.Client.Close()
}

// FinishTaskRecursively finishes all open descendant tasks using default context
func (a *App) FinishTaskRecursively(task *ent.Task) error {
	return a.TaskService.FinishTaskRecursively(a.ctx, task)
}
