// Code generated by ent, DO NOT EDIT.

package directionsubmission

import (
	"arturgudiev/dashboard/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldLTE(FieldID, id))
}

// DirectionID applies equality check predicate on the "direction_id" field. It's identical to DirectionIDEQ.
func DirectionID(v int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldEQ(FieldDirectionID, v))
}

// ExecutionDate applies equality check predicate on the "execution_date" field. It's identical to ExecutionDateEQ.
func ExecutionDate(v time.Time) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldEQ(FieldExecutionDate, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldEQ(FieldText, v))
}

// DirectionIDEQ applies the EQ predicate on the "direction_id" field.
func DirectionIDEQ(v int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldEQ(FieldDirectionID, v))
}

// DirectionIDNEQ applies the NEQ predicate on the "direction_id" field.
func DirectionIDNEQ(v int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldNEQ(FieldDirectionID, v))
}

// DirectionIDIn applies the In predicate on the "direction_id" field.
func DirectionIDIn(vs ...int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldIn(FieldDirectionID, vs...))
}

// DirectionIDNotIn applies the NotIn predicate on the "direction_id" field.
func DirectionIDNotIn(vs ...int) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldNotIn(FieldDirectionID, vs...))
}

// ExecutionDateEQ applies the EQ predicate on the "execution_date" field.
func ExecutionDateEQ(v time.Time) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldEQ(FieldExecutionDate, v))
}

// ExecutionDateNEQ applies the NEQ predicate on the "execution_date" field.
func ExecutionDateNEQ(v time.Time) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldNEQ(FieldExecutionDate, v))
}

// ExecutionDateIn applies the In predicate on the "execution_date" field.
func ExecutionDateIn(vs ...time.Time) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldIn(FieldExecutionDate, vs...))
}

// ExecutionDateNotIn applies the NotIn predicate on the "execution_date" field.
func ExecutionDateNotIn(vs ...time.Time) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldNotIn(FieldExecutionDate, vs...))
}

// ExecutionDateGT applies the GT predicate on the "execution_date" field.
func ExecutionDateGT(v time.Time) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldGT(FieldExecutionDate, v))
}

// ExecutionDateGTE applies the GTE predicate on the "execution_date" field.
func ExecutionDateGTE(v time.Time) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldGTE(FieldExecutionDate, v))
}

// ExecutionDateLT applies the LT predicate on the "execution_date" field.
func ExecutionDateLT(v time.Time) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldLT(FieldExecutionDate, v))
}

// ExecutionDateLTE applies the LTE predicate on the "execution_date" field.
func ExecutionDateLTE(v time.Time) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldLTE(FieldExecutionDate, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldHasSuffix(FieldText, v))
}

// TextIsNil applies the IsNil predicate on the "text" field.
func TextIsNil() predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldIsNull(FieldText))
}

// TextNotNil applies the NotNil predicate on the "text" field.
func TextNotNil() predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldNotNull(FieldText))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.FieldContainsFold(FieldText, v))
}

// HasDirection applies the HasEdge predicate on the "direction" edge.
func HasDirection() predicate.DirectionSubmission {
	return predicate.DirectionSubmission(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DirectionTable, DirectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDirectionWith applies the HasEdge predicate on the "direction" edge with a given conditions (other predicates).
func HasDirectionWith(preds ...predicate.Direction) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(func(s *sql.Selector) {
		step := newDirectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DirectionSubmission) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DirectionSubmission) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DirectionSubmission) predicate.DirectionSubmission {
	return predicate.DirectionSubmission(sql.NotPredicates(p))
}
