// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/containervariables"
	"arturgudiev/dashboard/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContainerVariablesDelete is the builder for deleting a ContainerVariables entity.
type ContainerVariablesDelete struct {
	config
	hooks    []Hook
	mutation *ContainerVariablesMutation
}

// Where appends a list predicates to the ContainerVariablesDelete builder.
func (_d *ContainerVariablesDelete) Where(ps ...predicate.ContainerVariables) *ContainerVariablesDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ContainerVariablesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContainerVariablesDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ContainerVariablesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(containervariables.Table, sqlgraph.NewFieldSpec(containervariables.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ContainerVariablesDeleteOne is the builder for deleting a single ContainerVariables entity.
type ContainerVariablesDeleteOne struct {
	_d *ContainerVariablesDelete
}

// Where appends a list predicates to the ContainerVariablesDelete builder.
func (_d *ContainerVariablesDeleteOne) Where(ps ...predicate.ContainerVariables) *ContainerVariablesDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ContainerVariablesDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{containervariables.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContainerVariablesDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
