// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/containervariables"
	"arturgudiev/dashboard/ent/variablesstack"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ContainerVariables is the model entity for the ContainerVariables schema.
type ContainerVariables struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// VariablesStackID holds the value of the "variables_stack_id" field.
	VariablesStackID int `json:"variables_stack_id,omitempty"`
	// VariableName holds the value of the "variable_name" field.
	VariableName string `json:"variable_name,omitempty"`
	// VariableValue holds the value of the "variable_value" field.
	VariableValue string `json:"variable_value,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContainerVariablesQuery when eager-loading is set.
	Edges        ContainerVariablesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContainerVariablesEdges holds the relations/edges for other nodes in the graph.
type ContainerVariablesEdges struct {
	// VariablesStack holds the value of the variables_stack edge.
	VariablesStack *VariablesStack `json:"variables_stack,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// VariablesStackOrErr returns the VariablesStack value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContainerVariablesEdges) VariablesStackOrErr() (*VariablesStack, error) {
	if e.VariablesStack != nil {
		return e.VariablesStack, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: variablesstack.Label}
	}
	return nil, &NotLoadedError{edge: "variables_stack"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContainerVariables) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case containervariables.FieldID, containervariables.FieldVariablesStackID:
			values[i] = new(sql.NullInt64)
		case containervariables.FieldVariableName, containervariables.FieldVariableValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContainerVariables fields.
func (_m *ContainerVariables) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case containervariables.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case containervariables.FieldVariablesStackID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field variables_stack_id", values[i])
			} else if value.Valid {
				_m.VariablesStackID = int(value.Int64)
			}
		case containervariables.FieldVariableName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field variable_name", values[i])
			} else if value.Valid {
				_m.VariableName = value.String
			}
		case containervariables.FieldVariableValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field variable_value", values[i])
			} else if value.Valid {
				_m.VariableValue = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContainerVariables.
// This includes values selected through modifiers, order, etc.
func (_m *ContainerVariables) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVariablesStack queries the "variables_stack" edge of the ContainerVariables entity.
func (_m *ContainerVariables) QueryVariablesStack() *VariablesStackQuery {
	return NewContainerVariablesClient(_m.config).QueryVariablesStack(_m)
}

// Update returns a builder for updating this ContainerVariables.
// Note that you need to call ContainerVariables.Unwrap() before calling this method if this ContainerVariables
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContainerVariables) Update() *ContainerVariablesUpdateOne {
	return NewContainerVariablesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContainerVariables entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContainerVariables) Unwrap() *ContainerVariables {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContainerVariables is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContainerVariables) String() string {
	var builder strings.Builder
	builder.WriteString("ContainerVariables(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("variables_stack_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VariablesStackID))
	builder.WriteString(", ")
	builder.WriteString("variable_name=")
	builder.WriteString(_m.VariableName)
	builder.WriteString(", ")
	builder.WriteString("variable_value=")
	builder.WriteString(_m.VariableValue)
	builder.WriteByte(')')
	return builder.String()
}

// ContainerVariablesSlice is a parsable slice of ContainerVariables.
type ContainerVariablesSlice []*ContainerVariables
