// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/containerchild"
	"arturgudiev/dashboard/ent/schema"
	"arturgudiev/dashboard/ent/task"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContainerChildCreate is the builder for creating a ContainerChild entity.
type ContainerChildCreate struct {
	config
	mutation *ContainerChildMutation
	hooks    []Hook
}

// SetParentType sets the "parent_type" field.
func (_c *ContainerChildCreate) SetParentType(v schema.ContainerType) *ContainerChildCreate {
	_c.mutation.SetParentType(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *ContainerChildCreate) SetParentID(v int) *ContainerChildCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetChildType sets the "child_type" field.
func (_c *ContainerChildCreate) SetChildType(v schema.ContainerType) *ContainerChildCreate {
	_c.mutation.SetChildType(v)
	return _c
}

// SetChildID sets the "child_id" field.
func (_c *ContainerChildCreate) SetChildID(v int) *ContainerChildCreate {
	_c.mutation.SetChildID(v)
	return _c
}

// SetChildOrder sets the "child_order" field.
func (_c *ContainerChildCreate) SetChildOrder(v int) *ContainerChildCreate {
	_c.mutation.SetChildOrder(v)
	return _c
}

// SetNillableChildOrder sets the "child_order" field if the given value is not nil.
func (_c *ContainerChildCreate) SetNillableChildOrder(v *int) *ContainerChildCreate {
	if v != nil {
		_c.SetChildOrder(*v)
	}
	return _c
}

// SetParentOrder sets the "parent_order" field.
func (_c *ContainerChildCreate) SetParentOrder(v int) *ContainerChildCreate {
	_c.mutation.SetParentOrder(v)
	return _c
}

// SetNillableParentOrder sets the "parent_order" field if the given value is not nil.
func (_c *ContainerChildCreate) SetNillableParentOrder(v *int) *ContainerChildCreate {
	if v != nil {
		_c.SetParentOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ContainerChildCreate) SetID(v int) *ContainerChildCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetParent sets the "parent" edge to the Task entity.
func (_c *ContainerChildCreate) SetParent(v *Task) *ContainerChildCreate {
	return _c.SetParentID(v.ID)
}

// SetChild sets the "child" edge to the Task entity.
func (_c *ContainerChildCreate) SetChild(v *Task) *ContainerChildCreate {
	return _c.SetChildID(v.ID)
}

// Mutation returns the ContainerChildMutation object of the builder.
func (_c *ContainerChildCreate) Mutation() *ContainerChildMutation {
	return _c.mutation
}

// Save creates the ContainerChild in the database.
func (_c *ContainerChildCreate) Save(ctx context.Context) (*ContainerChild, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContainerChildCreate) SaveX(ctx context.Context) *ContainerChild {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContainerChildCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContainerChildCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContainerChildCreate) defaults() {
	if _, ok := _c.mutation.ChildOrder(); !ok {
		v := containerchild.DefaultChildOrder
		_c.mutation.SetChildOrder(v)
	}
	if _, ok := _c.mutation.ParentOrder(); !ok {
		v := containerchild.DefaultParentOrder
		_c.mutation.SetParentOrder(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContainerChildCreate) check() error {
	if _, ok := _c.mutation.ParentType(); !ok {
		return &ValidationError{Name: "parent_type", err: errors.New(`ent: missing required field "ContainerChild.parent_type"`)}
	}
	if v, ok := _c.mutation.ParentType(); ok {
		if err := containerchild.ParentTypeValidator(v); err != nil {
			return &ValidationError{Name: "parent_type", err: fmt.Errorf(`ent: validator failed for field "ContainerChild.parent_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "ContainerChild.parent_id"`)}
	}
	if v, ok := _c.mutation.ParentID(); ok {
		if err := containerchild.ParentIDValidator(v); err != nil {
			return &ValidationError{Name: "parent_id", err: fmt.Errorf(`ent: validator failed for field "ContainerChild.parent_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChildType(); !ok {
		return &ValidationError{Name: "child_type", err: errors.New(`ent: missing required field "ContainerChild.child_type"`)}
	}
	if v, ok := _c.mutation.ChildType(); ok {
		if err := containerchild.ChildTypeValidator(v); err != nil {
			return &ValidationError{Name: "child_type", err: fmt.Errorf(`ent: validator failed for field "ContainerChild.child_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChildID(); !ok {
		return &ValidationError{Name: "child_id", err: errors.New(`ent: missing required field "ContainerChild.child_id"`)}
	}
	if v, ok := _c.mutation.ChildID(); ok {
		if err := containerchild.ChildIDValidator(v); err != nil {
			return &ValidationError{Name: "child_id", err: fmt.Errorf(`ent: validator failed for field "ContainerChild.child_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChildOrder(); !ok {
		return &ValidationError{Name: "child_order", err: errors.New(`ent: missing required field "ContainerChild.child_order"`)}
	}
	if v, ok := _c.mutation.ChildOrder(); ok {
		if err := containerchild.ChildOrderValidator(v); err != nil {
			return &ValidationError{Name: "child_order", err: fmt.Errorf(`ent: validator failed for field "ContainerChild.child_order": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ParentOrder(); !ok {
		return &ValidationError{Name: "parent_order", err: errors.New(`ent: missing required field "ContainerChild.parent_order"`)}
	}
	if v, ok := _c.mutation.ParentOrder(); ok {
		if err := containerchild.ParentOrderValidator(v); err != nil {
			return &ValidationError{Name: "parent_order", err: fmt.Errorf(`ent: validator failed for field "ContainerChild.parent_order": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := containerchild.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ContainerChild.id": %w`, err)}
		}
	}
	if len(_c.mutation.ParentIDs()) == 0 {
		return &ValidationError{Name: "parent", err: errors.New(`ent: missing required edge "ContainerChild.parent"`)}
	}
	if len(_c.mutation.ChildIDs()) == 0 {
		return &ValidationError{Name: "child", err: errors.New(`ent: missing required edge "ContainerChild.child"`)}
	}
	return nil
}

func (_c *ContainerChildCreate) sqlSave(ctx context.Context) (*ContainerChild, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContainerChildCreate) createSpec() (*ContainerChild, *sqlgraph.CreateSpec) {
	var (
		_node = &ContainerChild{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(containerchild.Table, sqlgraph.NewFieldSpec(containerchild.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ParentType(); ok {
		_spec.SetField(containerchild.FieldParentType, field.TypeEnum, value)
		_node.ParentType = value
	}
	if value, ok := _c.mutation.ChildType(); ok {
		_spec.SetField(containerchild.FieldChildType, field.TypeEnum, value)
		_node.ChildType = value
	}
	if value, ok := _c.mutation.ChildOrder(); ok {
		_spec.SetField(containerchild.FieldChildOrder, field.TypeInt, value)
		_node.ChildOrder = value
	}
	if value, ok := _c.mutation.ParentOrder(); ok {
		_spec.SetField(containerchild.FieldParentOrder, field.TypeInt, value)
		_node.ParentOrder = value
	}
	if nodes := _c.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   containerchild.ParentTable,
			Columns: []string{containerchild.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ParentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChildIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   containerchild.ChildTable,
			Columns: []string{containerchild.ChildColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChildID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ContainerChildCreateBulk is the builder for creating many ContainerChild entities in bulk.
type ContainerChildCreateBulk struct {
	config
	err      error
	builders []*ContainerChildCreate
}

// Save creates the ContainerChild entities in the database.
func (_c *ContainerChildCreateBulk) Save(ctx context.Context) ([]*ContainerChild, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContainerChild, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContainerChildMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContainerChildCreateBulk) SaveX(ctx context.Context) []*ContainerChild {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContainerChildCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContainerChildCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
