// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/containerchild"
	"arturgudiev/dashboard/ent/schema"
	"arturgudiev/dashboard/ent/task"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ContainerChild is the model entity for the ContainerChild schema.
type ContainerChild struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ParentType holds the value of the "parent_type" field.
	ParentType schema.ContainerType `json:"parent_type,omitempty"`
	// ParentID holds the value of the "parent_id" field.
	ParentID int `json:"parent_id,omitempty"`
	// ChildType holds the value of the "child_type" field.
	ChildType schema.ContainerType `json:"child_type,omitempty"`
	// ChildID holds the value of the "child_id" field.
	ChildID int `json:"child_id,omitempty"`
	// ChildOrder holds the value of the "child_order" field.
	ChildOrder int `json:"child_order,omitempty"`
	// ParentOrder holds the value of the "parent_order" field.
	ParentOrder int `json:"parent_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContainerChildQuery when eager-loading is set.
	Edges        ContainerChildEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContainerChildEdges holds the relations/edges for other nodes in the graph.
type ContainerChildEdges struct {
	// Parent holds the value of the parent edge.
	Parent *Task `json:"parent,omitempty"`
	// Child holds the value of the child edge.
	Child *Task `json:"child,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContainerChildEdges) ParentOrErr() (*Task, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// ChildOrErr returns the Child value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContainerChildEdges) ChildOrErr() (*Task, error) {
	if e.Child != nil {
		return e.Child, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: task.Label}
	}
	return nil, &NotLoadedError{edge: "child"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContainerChild) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case containerchild.FieldID, containerchild.FieldParentID, containerchild.FieldChildID, containerchild.FieldChildOrder, containerchild.FieldParentOrder:
			values[i] = new(sql.NullInt64)
		case containerchild.FieldParentType, containerchild.FieldChildType:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContainerChild fields.
func (_m *ContainerChild) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case containerchild.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case containerchild.FieldParentType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parent_type", values[i])
			} else if value.Valid {
				_m.ParentType = schema.ContainerType(value.String)
			}
		case containerchild.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = int(value.Int64)
			}
		case containerchild.FieldChildType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field child_type", values[i])
			} else if value.Valid {
				_m.ChildType = schema.ContainerType(value.String)
			}
		case containerchild.FieldChildID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field child_id", values[i])
			} else if value.Valid {
				_m.ChildID = int(value.Int64)
			}
		case containerchild.FieldChildOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field child_order", values[i])
			} else if value.Valid {
				_m.ChildOrder = int(value.Int64)
			}
		case containerchild.FieldParentOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_order", values[i])
			} else if value.Valid {
				_m.ParentOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContainerChild.
// This includes values selected through modifiers, order, etc.
func (_m *ContainerChild) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryParent queries the "parent" edge of the ContainerChild entity.
func (_m *ContainerChild) QueryParent() *TaskQuery {
	return NewContainerChildClient(_m.config).QueryParent(_m)
}

// QueryChild queries the "child" edge of the ContainerChild entity.
func (_m *ContainerChild) QueryChild() *TaskQuery {
	return NewContainerChildClient(_m.config).QueryChild(_m)
}

// Update returns a builder for updating this ContainerChild.
// Note that you need to call ContainerChild.Unwrap() before calling this method if this ContainerChild
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContainerChild) Update() *ContainerChildUpdateOne {
	return NewContainerChildClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContainerChild entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContainerChild) Unwrap() *ContainerChild {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContainerChild is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContainerChild) String() string {
	var builder strings.Builder
	builder.WriteString("ContainerChild(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("parent_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentType))
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteString(", ")
	builder.WriteString("child_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChildType))
	builder.WriteString(", ")
	builder.WriteString("child_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChildID))
	builder.WriteString(", ")
	builder.WriteString("child_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChildOrder))
	builder.WriteString(", ")
	builder.WriteString("parent_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentOrder))
	builder.WriteByte(')')
	return builder.String()
}

// ContainerChilds is a parsable slice of ContainerChild.
type ContainerChilds []*ContainerChild
