// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/longtaskprogress"
	"arturgudiev/dashboard/ent/longtaskprogresssubmission"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LongTaskProgressSubmission is the model entity for the LongTaskProgressSubmission schema.
type LongTaskProgressSubmission struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Comments holds the value of the "comments" field.
	Comments string `json:"comments,omitempty"`
	// ProgressToAdd holds the value of the "progress_to_add" field.
	ProgressToAdd *int `json:"progress_to_add,omitempty"`
	// ProgressToSet holds the value of the "progress_to_set" field.
	ProgressToSet *float64 `json:"progress_to_set,omitempty"`
	// ProgressRaw holds the value of the "progress_raw" field.
	ProgressRaw *float64 `json:"progress_raw,omitempty"`
	// ExecutionDate holds the value of the "execution_date" field.
	ExecutionDate time.Time `json:"execution_date,omitempty"`
	// LongTaskProgressID holds the value of the "long_task_progress_id" field.
	LongTaskProgressID int `json:"long_task_progress_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LongTaskProgressSubmissionQuery when eager-loading is set.
	Edges        LongTaskProgressSubmissionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LongTaskProgressSubmissionEdges holds the relations/edges for other nodes in the graph.
type LongTaskProgressSubmissionEdges struct {
	// LongTaskProgress holds the value of the long_task_progress edge.
	LongTaskProgress *LongTaskProgress `json:"long_task_progress,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LongTaskProgressOrErr returns the LongTaskProgress value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LongTaskProgressSubmissionEdges) LongTaskProgressOrErr() (*LongTaskProgress, error) {
	if e.LongTaskProgress != nil {
		return e.LongTaskProgress, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: longtaskprogress.Label}
	}
	return nil, &NotLoadedError{edge: "long_task_progress"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LongTaskProgressSubmission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case longtaskprogresssubmission.FieldProgressToSet, longtaskprogresssubmission.FieldProgressRaw:
			values[i] = new(sql.NullFloat64)
		case longtaskprogresssubmission.FieldID, longtaskprogresssubmission.FieldProgressToAdd, longtaskprogresssubmission.FieldLongTaskProgressID:
			values[i] = new(sql.NullInt64)
		case longtaskprogresssubmission.FieldComments:
			values[i] = new(sql.NullString)
		case longtaskprogresssubmission.FieldExecutionDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LongTaskProgressSubmission fields.
func (_m *LongTaskProgressSubmission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case longtaskprogresssubmission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case longtaskprogresssubmission.FieldComments:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field comments", values[i])
			} else if value.Valid {
				_m.Comments = value.String
			}
		case longtaskprogresssubmission.FieldProgressToAdd:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress_to_add", values[i])
			} else if value.Valid {
				_m.ProgressToAdd = new(int)
				*_m.ProgressToAdd = int(value.Int64)
			}
		case longtaskprogresssubmission.FieldProgressToSet:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field progress_to_set", values[i])
			} else if value.Valid {
				_m.ProgressToSet = new(float64)
				*_m.ProgressToSet = value.Float64
			}
		case longtaskprogresssubmission.FieldProgressRaw:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field progress_raw", values[i])
			} else if value.Valid {
				_m.ProgressRaw = new(float64)
				*_m.ProgressRaw = value.Float64
			}
		case longtaskprogresssubmission.FieldExecutionDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field execution_date", values[i])
			} else if value.Valid {
				_m.ExecutionDate = value.Time
			}
		case longtaskprogresssubmission.FieldLongTaskProgressID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field long_task_progress_id", values[i])
			} else if value.Valid {
				_m.LongTaskProgressID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LongTaskProgressSubmission.
// This includes values selected through modifiers, order, etc.
func (_m *LongTaskProgressSubmission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLongTaskProgress queries the "long_task_progress" edge of the LongTaskProgressSubmission entity.
func (_m *LongTaskProgressSubmission) QueryLongTaskProgress() *LongTaskProgressQuery {
	return NewLongTaskProgressSubmissionClient(_m.config).QueryLongTaskProgress(_m)
}

// Update returns a builder for updating this LongTaskProgressSubmission.
// Note that you need to call LongTaskProgressSubmission.Unwrap() before calling this method if this LongTaskProgressSubmission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LongTaskProgressSubmission) Update() *LongTaskProgressSubmissionUpdateOne {
	return NewLongTaskProgressSubmissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LongTaskProgressSubmission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LongTaskProgressSubmission) Unwrap() *LongTaskProgressSubmission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LongTaskProgressSubmission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LongTaskProgressSubmission) String() string {
	var builder strings.Builder
	builder.WriteString("LongTaskProgressSubmission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("comments=")
	builder.WriteString(_m.Comments)
	builder.WriteString(", ")
	if v := _m.ProgressToAdd; v != nil {
		builder.WriteString("progress_to_add=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProgressToSet; v != nil {
		builder.WriteString("progress_to_set=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProgressRaw; v != nil {
		builder.WriteString("progress_raw=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("execution_date=")
	builder.WriteString(_m.ExecutionDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("long_task_progress_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LongTaskProgressID))
	builder.WriteByte(')')
	return builder.String()
}

// LongTaskProgressSubmissions is a parsable slice of LongTaskProgressSubmission.
type LongTaskProgressSubmissions []*LongTaskProgressSubmission
