// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/longtask"
	"arturgudiev/dashboard/ent/longtaskprogress"
	"arturgudiev/dashboard/ent/longtasksubmission"
	"arturgudiev/dashboard/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LongTaskQuery is the builder for querying LongTask entities.
type LongTaskQuery struct {
	config
	ctx             *QueryContext
	order           []longtask.OrderOption
	inters          []Interceptor
	predicates      []predicate.LongTask
	withSubmissions *LongTaskSubmissionQuery
	withProgresses  *LongTaskProgressQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LongTaskQuery builder.
func (_q *LongTaskQuery) Where(ps ...predicate.LongTask) *LongTaskQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LongTaskQuery) Limit(limit int) *LongTaskQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LongTaskQuery) Offset(offset int) *LongTaskQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LongTaskQuery) Unique(unique bool) *LongTaskQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LongTaskQuery) Order(o ...longtask.OrderOption) *LongTaskQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySubmissions chains the current query on the "submissions" edge.
func (_q *LongTaskQuery) QuerySubmissions() *LongTaskSubmissionQuery {
	query := (&LongTaskSubmissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(longtask.Table, longtask.FieldID, selector),
			sqlgraph.To(longtasksubmission.Table, longtasksubmission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, longtask.SubmissionsTable, longtask.SubmissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProgresses chains the current query on the "progresses" edge.
func (_q *LongTaskQuery) QueryProgresses() *LongTaskProgressQuery {
	query := (&LongTaskProgressClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(longtask.Table, longtask.FieldID, selector),
			sqlgraph.To(longtaskprogress.Table, longtaskprogress.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, longtask.ProgressesTable, longtask.ProgressesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LongTask entity from the query.
// Returns a *NotFoundError when no LongTask was found.
func (_q *LongTaskQuery) First(ctx context.Context) (*LongTask, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{longtask.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LongTaskQuery) FirstX(ctx context.Context) *LongTask {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LongTask ID from the query.
// Returns a *NotFoundError when no LongTask ID was found.
func (_q *LongTaskQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{longtask.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LongTaskQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LongTask entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LongTask entity is found.
// Returns a *NotFoundError when no LongTask entities are found.
func (_q *LongTaskQuery) Only(ctx context.Context) (*LongTask, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{longtask.Label}
	default:
		return nil, &NotSingularError{longtask.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LongTaskQuery) OnlyX(ctx context.Context) *LongTask {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LongTask ID in the query.
// Returns a *NotSingularError when more than one LongTask ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LongTaskQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{longtask.Label}
	default:
		err = &NotSingularError{longtask.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LongTaskQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LongTasks.
func (_q *LongTaskQuery) All(ctx context.Context) ([]*LongTask, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LongTask, *LongTaskQuery]()
	return withInterceptors[[]*LongTask](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LongTaskQuery) AllX(ctx context.Context) []*LongTask {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LongTask IDs.
func (_q *LongTaskQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(longtask.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LongTaskQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LongTaskQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LongTaskQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LongTaskQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LongTaskQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LongTaskQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LongTaskQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LongTaskQuery) Clone() *LongTaskQuery {
	if _q == nil {
		return nil
	}
	return &LongTaskQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]longtask.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.LongTask{}, _q.predicates...),
		withSubmissions: _q.withSubmissions.Clone(),
		withProgresses:  _q.withProgresses.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSubmissions tells the query-builder to eager-load the nodes that are connected to
// the "submissions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LongTaskQuery) WithSubmissions(opts ...func(*LongTaskSubmissionQuery)) *LongTaskQuery {
	query := (&LongTaskSubmissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubmissions = query
	return _q
}

// WithProgresses tells the query-builder to eager-load the nodes that are connected to
// the "progresses" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LongTaskQuery) WithProgresses(opts ...func(*LongTaskProgressQuery)) *LongTaskQuery {
	query := (&LongTaskProgressClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProgresses = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Description string `json:"description" binding:"required"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LongTask.Query().
//		GroupBy(longtask.FieldDescription).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LongTaskQuery) GroupBy(field string, fields ...string) *LongTaskGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LongTaskGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = longtask.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Description string `json:"description" binding:"required"`
//	}
//
//	client.LongTask.Query().
//		Select(longtask.FieldDescription).
//		Scan(ctx, &v)
func (_q *LongTaskQuery) Select(fields ...string) *LongTaskSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LongTaskSelect{LongTaskQuery: _q}
	sbuild.label = longtask.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LongTaskSelect configured with the given aggregations.
func (_q *LongTaskQuery) Aggregate(fns ...AggregateFunc) *LongTaskSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LongTaskQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !longtask.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LongTaskQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LongTask, error) {
	var (
		nodes       = []*LongTask{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withSubmissions != nil,
			_q.withProgresses != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LongTask).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LongTask{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSubmissions; query != nil {
		if err := _q.loadSubmissions(ctx, query, nodes,
			func(n *LongTask) { n.Edges.Submissions = []*LongTaskSubmission{} },
			func(n *LongTask, e *LongTaskSubmission) { n.Edges.Submissions = append(n.Edges.Submissions, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProgresses; query != nil {
		if err := _q.loadProgresses(ctx, query, nodes,
			func(n *LongTask) { n.Edges.Progresses = []*LongTaskProgress{} },
			func(n *LongTask, e *LongTaskProgress) { n.Edges.Progresses = append(n.Edges.Progresses, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LongTaskQuery) loadSubmissions(ctx context.Context, query *LongTaskSubmissionQuery, nodes []*LongTask, init func(*LongTask), assign func(*LongTask, *LongTaskSubmission)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LongTask)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(longtasksubmission.FieldLongTaskID)
	}
	query.Where(predicate.LongTaskSubmission(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(longtask.SubmissionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LongTaskID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "long_task_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *LongTaskQuery) loadProgresses(ctx context.Context, query *LongTaskProgressQuery, nodes []*LongTask, init func(*LongTask), assign func(*LongTask, *LongTaskProgress)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LongTask)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(longtaskprogress.FieldLongTaskID)
	}
	query.Where(predicate.LongTaskProgress(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(longtask.ProgressesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LongTaskID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "long_task_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *LongTaskQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LongTaskQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(longtask.Table, longtask.Columns, sqlgraph.NewFieldSpec(longtask.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, longtask.FieldID)
		for i := range fields {
			if fields[i] != longtask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LongTaskQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(longtask.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = longtask.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LongTaskGroupBy is the group-by builder for LongTask entities.
type LongTaskGroupBy struct {
	selector
	build *LongTaskQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LongTaskGroupBy) Aggregate(fns ...AggregateFunc) *LongTaskGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LongTaskGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LongTaskQuery, *LongTaskGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LongTaskGroupBy) sqlScan(ctx context.Context, root *LongTaskQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LongTaskSelect is the builder for selecting fields of LongTask entities.
type LongTaskSelect struct {
	*LongTaskQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LongTaskSelect) Aggregate(fns ...AggregateFunc) *LongTaskSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LongTaskSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LongTaskQuery, *LongTaskSelect](ctx, _s.LongTaskQuery, _s, _s.inters, v)
}

func (_s *LongTaskSelect) sqlScan(ctx context.Context, root *LongTaskQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
