// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/longtask"
	"arturgudiev/dashboard/ent/longtasksubmission"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LongTaskSubmissionCreate is the builder for creating a LongTaskSubmission entity.
type LongTaskSubmissionCreate struct {
	config
	mutation *LongTaskSubmissionMutation
	hooks    []Hook
}

// SetLongTaskID sets the "long_task_id" field.
func (_c *LongTaskSubmissionCreate) SetLongTaskID(v int) *LongTaskSubmissionCreate {
	_c.mutation.SetLongTaskID(v)
	return _c
}

// SetExecutionDate sets the "execution_date" field.
func (_c *LongTaskSubmissionCreate) SetExecutionDate(v time.Time) *LongTaskSubmissionCreate {
	_c.mutation.SetExecutionDate(v)
	return _c
}

// SetComments sets the "comments" field.
func (_c *LongTaskSubmissionCreate) SetComments(v string) *LongTaskSubmissionCreate {
	_c.mutation.SetComments(v)
	return _c
}

// SetNillableComments sets the "comments" field if the given value is not nil.
func (_c *LongTaskSubmissionCreate) SetNillableComments(v *string) *LongTaskSubmissionCreate {
	if v != nil {
		_c.SetComments(*v)
	}
	return _c
}

// SetProgressToAdd sets the "progress_to_add" field.
func (_c *LongTaskSubmissionCreate) SetProgressToAdd(v float64) *LongTaskSubmissionCreate {
	_c.mutation.SetProgressToAdd(v)
	return _c
}

// SetNillableProgressToAdd sets the "progress_to_add" field if the given value is not nil.
func (_c *LongTaskSubmissionCreate) SetNillableProgressToAdd(v *float64) *LongTaskSubmissionCreate {
	if v != nil {
		_c.SetProgressToAdd(*v)
	}
	return _c
}

// SetProgressToSet sets the "progress_to_set" field.
func (_c *LongTaskSubmissionCreate) SetProgressToSet(v float64) *LongTaskSubmissionCreate {
	_c.mutation.SetProgressToSet(v)
	return _c
}

// SetNillableProgressToSet sets the "progress_to_set" field if the given value is not nil.
func (_c *LongTaskSubmissionCreate) SetNillableProgressToSet(v *float64) *LongTaskSubmissionCreate {
	if v != nil {
		_c.SetProgressToSet(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LongTaskSubmissionCreate) SetID(v int) *LongTaskSubmissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetLongTask sets the "long_task" edge to the LongTask entity.
func (_c *LongTaskSubmissionCreate) SetLongTask(v *LongTask) *LongTaskSubmissionCreate {
	return _c.SetLongTaskID(v.ID)
}

// Mutation returns the LongTaskSubmissionMutation object of the builder.
func (_c *LongTaskSubmissionCreate) Mutation() *LongTaskSubmissionMutation {
	return _c.mutation
}

// Save creates the LongTaskSubmission in the database.
func (_c *LongTaskSubmissionCreate) Save(ctx context.Context) (*LongTaskSubmission, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LongTaskSubmissionCreate) SaveX(ctx context.Context) *LongTaskSubmission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LongTaskSubmissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LongTaskSubmissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LongTaskSubmissionCreate) check() error {
	if _, ok := _c.mutation.LongTaskID(); !ok {
		return &ValidationError{Name: "long_task_id", err: errors.New(`ent: missing required field "LongTaskSubmission.long_task_id"`)}
	}
	if v, ok := _c.mutation.LongTaskID(); ok {
		if err := longtasksubmission.LongTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "long_task_id", err: fmt.Errorf(`ent: validator failed for field "LongTaskSubmission.long_task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecutionDate(); !ok {
		return &ValidationError{Name: "execution_date", err: errors.New(`ent: missing required field "LongTaskSubmission.execution_date"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := longtasksubmission.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "LongTaskSubmission.id": %w`, err)}
		}
	}
	if len(_c.mutation.LongTaskIDs()) == 0 {
		return &ValidationError{Name: "long_task", err: errors.New(`ent: missing required edge "LongTaskSubmission.long_task"`)}
	}
	return nil
}

func (_c *LongTaskSubmissionCreate) sqlSave(ctx context.Context) (*LongTaskSubmission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LongTaskSubmissionCreate) createSpec() (*LongTaskSubmission, *sqlgraph.CreateSpec) {
	var (
		_node = &LongTaskSubmission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(longtasksubmission.Table, sqlgraph.NewFieldSpec(longtasksubmission.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ExecutionDate(); ok {
		_spec.SetField(longtasksubmission.FieldExecutionDate, field.TypeTime, value)
		_node.ExecutionDate = value
	}
	if value, ok := _c.mutation.Comments(); ok {
		_spec.SetField(longtasksubmission.FieldComments, field.TypeString, value)
		_node.Comments = &value
	}
	if value, ok := _c.mutation.ProgressToAdd(); ok {
		_spec.SetField(longtasksubmission.FieldProgressToAdd, field.TypeFloat64, value)
		_node.ProgressToAdd = &value
	}
	if value, ok := _c.mutation.ProgressToSet(); ok {
		_spec.SetField(longtasksubmission.FieldProgressToSet, field.TypeFloat64, value)
		_node.ProgressToSet = &value
	}
	if nodes := _c.mutation.LongTaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   longtasksubmission.LongTaskTable,
			Columns: []string{longtasksubmission.LongTaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(longtask.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LongTaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LongTaskSubmissionCreateBulk is the builder for creating many LongTaskSubmission entities in bulk.
type LongTaskSubmissionCreateBulk struct {
	config
	err      error
	builders []*LongTaskSubmissionCreate
}

// Save creates the LongTaskSubmission entities in the database.
func (_c *LongTaskSubmissionCreateBulk) Save(ctx context.Context) ([]*LongTaskSubmission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LongTaskSubmission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LongTaskSubmissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LongTaskSubmissionCreateBulk) SaveX(ctx context.Context) []*LongTaskSubmission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LongTaskSubmissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LongTaskSubmissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
