// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/longtaskprogresssubmission"
	"arturgudiev/dashboard/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LongTaskProgressSubmissionDelete is the builder for deleting a LongTaskProgressSubmission entity.
type LongTaskProgressSubmissionDelete struct {
	config
	hooks    []Hook
	mutation *LongTaskProgressSubmissionMutation
}

// Where appends a list predicates to the LongTaskProgressSubmissionDelete builder.
func (_d *LongTaskProgressSubmissionDelete) Where(ps ...predicate.LongTaskProgressSubmission) *LongTaskProgressSubmissionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LongTaskProgressSubmissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LongTaskProgressSubmissionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LongTaskProgressSubmissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(longtaskprogresssubmission.Table, sqlgraph.NewFieldSpec(longtaskprogresssubmission.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LongTaskProgressSubmissionDeleteOne is the builder for deleting a single LongTaskProgressSubmission entity.
type LongTaskProgressSubmissionDeleteOne struct {
	_d *LongTaskProgressSubmissionDelete
}

// Where appends a list predicates to the LongTaskProgressSubmissionDelete builder.
func (_d *LongTaskProgressSubmissionDeleteOne) Where(ps ...predicate.LongTaskProgressSubmission) *LongTaskProgressSubmissionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LongTaskProgressSubmissionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{longtaskprogresssubmission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LongTaskProgressSubmissionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
