// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/longtask"
	"arturgudiev/dashboard/ent/longtaskprogress"
	"arturgudiev/dashboard/ent/longtaskprogresssubmission"
	"arturgudiev/dashboard/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LongTaskProgressQuery is the builder for querying LongTaskProgress entities.
type LongTaskProgressQuery struct {
	config
	ctx                     *QueryContext
	order                   []longtaskprogress.OrderOption
	inters                  []Interceptor
	predicates              []predicate.LongTaskProgress
	withLongTask            *LongTaskQuery
	withProgressSubmissions *LongTaskProgressSubmissionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LongTaskProgressQuery builder.
func (_q *LongTaskProgressQuery) Where(ps ...predicate.LongTaskProgress) *LongTaskProgressQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *LongTaskProgressQuery) Limit(limit int) *LongTaskProgressQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *LongTaskProgressQuery) Offset(offset int) *LongTaskProgressQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *LongTaskProgressQuery) Unique(unique bool) *LongTaskProgressQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *LongTaskProgressQuery) Order(o ...longtaskprogress.OrderOption) *LongTaskProgressQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryLongTask chains the current query on the "long_task" edge.
func (_q *LongTaskProgressQuery) QueryLongTask() *LongTaskQuery {
	query := (&LongTaskClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(longtaskprogress.Table, longtaskprogress.FieldID, selector),
			sqlgraph.To(longtask.Table, longtask.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, longtaskprogress.LongTaskTable, longtaskprogress.LongTaskColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProgressSubmissions chains the current query on the "progress_submissions" edge.
func (_q *LongTaskProgressQuery) QueryProgressSubmissions() *LongTaskProgressSubmissionQuery {
	query := (&LongTaskProgressSubmissionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(longtaskprogress.Table, longtaskprogress.FieldID, selector),
			sqlgraph.To(longtaskprogresssubmission.Table, longtaskprogresssubmission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, longtaskprogress.ProgressSubmissionsTable, longtaskprogress.ProgressSubmissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LongTaskProgress entity from the query.
// Returns a *NotFoundError when no LongTaskProgress was found.
func (_q *LongTaskProgressQuery) First(ctx context.Context) (*LongTaskProgress, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{longtaskprogress.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *LongTaskProgressQuery) FirstX(ctx context.Context) *LongTaskProgress {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LongTaskProgress ID from the query.
// Returns a *NotFoundError when no LongTaskProgress ID was found.
func (_q *LongTaskProgressQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{longtaskprogress.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *LongTaskProgressQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LongTaskProgress entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LongTaskProgress entity is found.
// Returns a *NotFoundError when no LongTaskProgress entities are found.
func (_q *LongTaskProgressQuery) Only(ctx context.Context) (*LongTaskProgress, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{longtaskprogress.Label}
	default:
		return nil, &NotSingularError{longtaskprogress.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *LongTaskProgressQuery) OnlyX(ctx context.Context) *LongTaskProgress {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LongTaskProgress ID in the query.
// Returns a *NotSingularError when more than one LongTaskProgress ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *LongTaskProgressQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{longtaskprogress.Label}
	default:
		err = &NotSingularError{longtaskprogress.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *LongTaskProgressQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LongTaskProgresses.
func (_q *LongTaskProgressQuery) All(ctx context.Context) ([]*LongTaskProgress, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LongTaskProgress, *LongTaskProgressQuery]()
	return withInterceptors[[]*LongTaskProgress](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *LongTaskProgressQuery) AllX(ctx context.Context) []*LongTaskProgress {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LongTaskProgress IDs.
func (_q *LongTaskProgressQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(longtaskprogress.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *LongTaskProgressQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *LongTaskProgressQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*LongTaskProgressQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *LongTaskProgressQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *LongTaskProgressQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *LongTaskProgressQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LongTaskProgressQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *LongTaskProgressQuery) Clone() *LongTaskProgressQuery {
	if _q == nil {
		return nil
	}
	return &LongTaskProgressQuery{
		config:                  _q.config,
		ctx:                     _q.ctx.Clone(),
		order:                   append([]longtaskprogress.OrderOption{}, _q.order...),
		inters:                  append([]Interceptor{}, _q.inters...),
		predicates:              append([]predicate.LongTaskProgress{}, _q.predicates...),
		withLongTask:            _q.withLongTask.Clone(),
		withProgressSubmissions: _q.withProgressSubmissions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithLongTask tells the query-builder to eager-load the nodes that are connected to
// the "long_task" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LongTaskProgressQuery) WithLongTask(opts ...func(*LongTaskQuery)) *LongTaskProgressQuery {
	query := (&LongTaskClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLongTask = query
	return _q
}

// WithProgressSubmissions tells the query-builder to eager-load the nodes that are connected to
// the "progress_submissions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *LongTaskProgressQuery) WithProgressSubmissions(opts ...func(*LongTaskProgressSubmissionQuery)) *LongTaskProgressQuery {
	query := (&LongTaskProgressSubmissionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProgressSubmissions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LongTaskProgress.Query().
//		GroupBy(longtaskprogress.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *LongTaskProgressQuery) GroupBy(field string, fields ...string) *LongTaskProgressGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LongTaskProgressGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = longtaskprogress.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.LongTaskProgress.Query().
//		Select(longtaskprogress.FieldName).
//		Scan(ctx, &v)
func (_q *LongTaskProgressQuery) Select(fields ...string) *LongTaskProgressSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &LongTaskProgressSelect{LongTaskProgressQuery: _q}
	sbuild.label = longtaskprogress.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LongTaskProgressSelect configured with the given aggregations.
func (_q *LongTaskProgressQuery) Aggregate(fns ...AggregateFunc) *LongTaskProgressSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *LongTaskProgressQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !longtaskprogress.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *LongTaskProgressQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LongTaskProgress, error) {
	var (
		nodes       = []*LongTaskProgress{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withLongTask != nil,
			_q.withProgressSubmissions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LongTaskProgress).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LongTaskProgress{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withLongTask; query != nil {
		if err := _q.loadLongTask(ctx, query, nodes, nil,
			func(n *LongTaskProgress, e *LongTask) { n.Edges.LongTask = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProgressSubmissions; query != nil {
		if err := _q.loadProgressSubmissions(ctx, query, nodes,
			func(n *LongTaskProgress) { n.Edges.ProgressSubmissions = []*LongTaskProgressSubmission{} },
			func(n *LongTaskProgress, e *LongTaskProgressSubmission) {
				n.Edges.ProgressSubmissions = append(n.Edges.ProgressSubmissions, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *LongTaskProgressQuery) loadLongTask(ctx context.Context, query *LongTaskQuery, nodes []*LongTaskProgress, init func(*LongTaskProgress), assign func(*LongTaskProgress, *LongTask)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LongTaskProgress)
	for i := range nodes {
		fk := nodes[i].LongTaskID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(longtask.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "long_task_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *LongTaskProgressQuery) loadProgressSubmissions(ctx context.Context, query *LongTaskProgressSubmissionQuery, nodes []*LongTaskProgress, init func(*LongTaskProgress), assign func(*LongTaskProgress, *LongTaskProgressSubmission)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*LongTaskProgress)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(longtaskprogresssubmission.FieldLongTaskProgressID)
	}
	query.Where(predicate.LongTaskProgressSubmission(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(longtaskprogress.ProgressSubmissionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.LongTaskProgressID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "long_task_progress_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *LongTaskProgressQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *LongTaskProgressQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(longtaskprogress.Table, longtaskprogress.Columns, sqlgraph.NewFieldSpec(longtaskprogress.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, longtaskprogress.FieldID)
		for i := range fields {
			if fields[i] != longtaskprogress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withLongTask != nil {
			_spec.Node.AddColumnOnce(longtaskprogress.FieldLongTaskID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *LongTaskProgressQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(longtaskprogress.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = longtaskprogress.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LongTaskProgressGroupBy is the group-by builder for LongTaskProgress entities.
type LongTaskProgressGroupBy struct {
	selector
	build *LongTaskProgressQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *LongTaskProgressGroupBy) Aggregate(fns ...AggregateFunc) *LongTaskProgressGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *LongTaskProgressGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LongTaskProgressQuery, *LongTaskProgressGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *LongTaskProgressGroupBy) sqlScan(ctx context.Context, root *LongTaskProgressQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LongTaskProgressSelect is the builder for selecting fields of LongTaskProgress entities.
type LongTaskProgressSelect struct {
	*LongTaskProgressQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *LongTaskProgressSelect) Aggregate(fns ...AggregateFunc) *LongTaskProgressSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *LongTaskProgressSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LongTaskProgressQuery, *LongTaskProgressSelect](ctx, _s.LongTaskProgressQuery, _s, _s.inters, v)
}

func (_s *LongTaskProgressSelect) sqlScan(ctx context.Context, root *LongTaskProgressQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
