// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/predicate"
	"arturgudiev/dashboard/ent/repetitivetask"
	"arturgudiev/dashboard/ent/repetitivetaskexecution"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// RepetitiveTaskUpdate is the builder for updating RepetitiveTask entities.
type RepetitiveTaskUpdate struct {
	config
	hooks    []Hook
	mutation *RepetitiveTaskMutation
}

// Where appends a list predicates to the RepetitiveTaskUpdate builder.
func (_u *RepetitiveTaskUpdate) Where(ps ...predicate.RepetitiveTask) *RepetitiveTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDescription sets the "description" field.
func (_u *RepetitiveTaskUpdate) SetDescription(v string) *RepetitiveTaskUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepetitiveTaskUpdate) SetNillableDescription(v *string) *RepetitiveTaskUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *RepetitiveTaskUpdate) SetTags(v []string) *RepetitiveTaskUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *RepetitiveTaskUpdate) AppendTags(v []string) *RepetitiveTaskUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetClosed sets the "closed" field.
func (_u *RepetitiveTaskUpdate) SetClosed(v bool) *RepetitiveTaskUpdate {
	_u.mutation.SetClosed(v)
	return _u
}

// SetNillableClosed sets the "closed" field if the given value is not nil.
func (_u *RepetitiveTaskUpdate) SetNillableClosed(v *bool) *RepetitiveTaskUpdate {
	if v != nil {
		_u.SetClosed(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RepetitiveTaskUpdate) SetNotes(v string) *RepetitiveTaskUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RepetitiveTaskUpdate) SetNillableNotes(v *string) *RepetitiveTaskUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetOnceInDays sets the "once_in_days" field.
func (_u *RepetitiveTaskUpdate) SetOnceInDays(v int) *RepetitiveTaskUpdate {
	_u.mutation.ResetOnceInDays()
	_u.mutation.SetOnceInDays(v)
	return _u
}

// SetNillableOnceInDays sets the "once_in_days" field if the given value is not nil.
func (_u *RepetitiveTaskUpdate) SetNillableOnceInDays(v *int) *RepetitiveTaskUpdate {
	if v != nil {
		_u.SetOnceInDays(*v)
	}
	return _u
}

// AddOnceInDays adds value to the "once_in_days" field.
func (_u *RepetitiveTaskUpdate) AddOnceInDays(v int) *RepetitiveTaskUpdate {
	_u.mutation.AddOnceInDays(v)
	return _u
}

// ClearOnceInDays clears the value of the "once_in_days" field.
func (_u *RepetitiveTaskUpdate) ClearOnceInDays() *RepetitiveTaskUpdate {
	_u.mutation.ClearOnceInDays()
	return _u
}

// SetOnceInWeeks sets the "once_in_weeks" field.
func (_u *RepetitiveTaskUpdate) SetOnceInWeeks(v int) *RepetitiveTaskUpdate {
	_u.mutation.ResetOnceInWeeks()
	_u.mutation.SetOnceInWeeks(v)
	return _u
}

// SetNillableOnceInWeeks sets the "once_in_weeks" field if the given value is not nil.
func (_u *RepetitiveTaskUpdate) SetNillableOnceInWeeks(v *int) *RepetitiveTaskUpdate {
	if v != nil {
		_u.SetOnceInWeeks(*v)
	}
	return _u
}

// AddOnceInWeeks adds value to the "once_in_weeks" field.
func (_u *RepetitiveTaskUpdate) AddOnceInWeeks(v int) *RepetitiveTaskUpdate {
	_u.mutation.AddOnceInWeeks(v)
	return _u
}

// ClearOnceInWeeks clears the value of the "once_in_weeks" field.
func (_u *RepetitiveTaskUpdate) ClearOnceInWeeks() *RepetitiveTaskUpdate {
	_u.mutation.ClearOnceInWeeks()
	return _u
}

// SetOnceInMonths sets the "once_in_months" field.
func (_u *RepetitiveTaskUpdate) SetOnceInMonths(v int) *RepetitiveTaskUpdate {
	_u.mutation.ResetOnceInMonths()
	_u.mutation.SetOnceInMonths(v)
	return _u
}

// SetNillableOnceInMonths sets the "once_in_months" field if the given value is not nil.
func (_u *RepetitiveTaskUpdate) SetNillableOnceInMonths(v *int) *RepetitiveTaskUpdate {
	if v != nil {
		_u.SetOnceInMonths(*v)
	}
	return _u
}

// AddOnceInMonths adds value to the "once_in_months" field.
func (_u *RepetitiveTaskUpdate) AddOnceInMonths(v int) *RepetitiveTaskUpdate {
	_u.mutation.AddOnceInMonths(v)
	return _u
}

// ClearOnceInMonths clears the value of the "once_in_months" field.
func (_u *RepetitiveTaskUpdate) ClearOnceInMonths() *RepetitiveTaskUpdate {
	_u.mutation.ClearOnceInMonths()
	return _u
}

// AddExecutionIDs adds the "executions" edge to the RepetitiveTaskExecution entity by IDs.
func (_u *RepetitiveTaskUpdate) AddExecutionIDs(ids ...int) *RepetitiveTaskUpdate {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the RepetitiveTaskExecution entity.
func (_u *RepetitiveTaskUpdate) AddExecutions(v ...*RepetitiveTaskExecution) *RepetitiveTaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// Mutation returns the RepetitiveTaskMutation object of the builder.
func (_u *RepetitiveTaskUpdate) Mutation() *RepetitiveTaskMutation {
	return _u.mutation
}

// ClearExecutions clears all "executions" edges to the RepetitiveTaskExecution entity.
func (_u *RepetitiveTaskUpdate) ClearExecutions() *RepetitiveTaskUpdate {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to RepetitiveTaskExecution entities by IDs.
func (_u *RepetitiveTaskUpdate) RemoveExecutionIDs(ids ...int) *RepetitiveTaskUpdate {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to RepetitiveTaskExecution entities.
func (_u *RepetitiveTaskUpdate) RemoveExecutions(v ...*RepetitiveTaskExecution) *RepetitiveTaskUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RepetitiveTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepetitiveTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RepetitiveTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepetitiveTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepetitiveTaskUpdate) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := repetitivetask.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RepetitiveTask.description": %w`, err)}
		}
	}
	return nil
}

func (_u *RepetitiveTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repetitivetask.Table, repetitivetask.Columns, sqlgraph.NewFieldSpec(repetitivetask.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repetitivetask.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(repetitivetask.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, repetitivetask.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Closed(); ok {
		_spec.SetField(repetitivetask.FieldClosed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(repetitivetask.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnceInDays(); ok {
		_spec.SetField(repetitivetask.FieldOnceInDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOnceInDays(); ok {
		_spec.AddField(repetitivetask.FieldOnceInDays, field.TypeInt, value)
	}
	if _u.mutation.OnceInDaysCleared() {
		_spec.ClearField(repetitivetask.FieldOnceInDays, field.TypeInt)
	}
	if value, ok := _u.mutation.OnceInWeeks(); ok {
		_spec.SetField(repetitivetask.FieldOnceInWeeks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOnceInWeeks(); ok {
		_spec.AddField(repetitivetask.FieldOnceInWeeks, field.TypeInt, value)
	}
	if _u.mutation.OnceInWeeksCleared() {
		_spec.ClearField(repetitivetask.FieldOnceInWeeks, field.TypeInt)
	}
	if value, ok := _u.mutation.OnceInMonths(); ok {
		_spec.SetField(repetitivetask.FieldOnceInMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOnceInMonths(); ok {
		_spec.AddField(repetitivetask.FieldOnceInMonths, field.TypeInt, value)
	}
	if _u.mutation.OnceInMonthsCleared() {
		_spec.ClearField(repetitivetask.FieldOnceInMonths, field.TypeInt)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repetitivetask.ExecutionsTable,
			Columns: []string{repetitivetask.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repetitivetaskexecution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repetitivetask.ExecutionsTable,
			Columns: []string{repetitivetask.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repetitivetaskexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repetitivetask.ExecutionsTable,
			Columns: []string{repetitivetask.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repetitivetaskexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repetitivetask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RepetitiveTaskUpdateOne is the builder for updating a single RepetitiveTask entity.
type RepetitiveTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RepetitiveTaskMutation
}

// SetDescription sets the "description" field.
func (_u *RepetitiveTaskUpdateOne) SetDescription(v string) *RepetitiveTaskUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RepetitiveTaskUpdateOne) SetNillableDescription(v *string) *RepetitiveTaskUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *RepetitiveTaskUpdateOne) SetTags(v []string) *RepetitiveTaskUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *RepetitiveTaskUpdateOne) AppendTags(v []string) *RepetitiveTaskUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetClosed sets the "closed" field.
func (_u *RepetitiveTaskUpdateOne) SetClosed(v bool) *RepetitiveTaskUpdateOne {
	_u.mutation.SetClosed(v)
	return _u
}

// SetNillableClosed sets the "closed" field if the given value is not nil.
func (_u *RepetitiveTaskUpdateOne) SetNillableClosed(v *bool) *RepetitiveTaskUpdateOne {
	if v != nil {
		_u.SetClosed(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RepetitiveTaskUpdateOne) SetNotes(v string) *RepetitiveTaskUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RepetitiveTaskUpdateOne) SetNillableNotes(v *string) *RepetitiveTaskUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetOnceInDays sets the "once_in_days" field.
func (_u *RepetitiveTaskUpdateOne) SetOnceInDays(v int) *RepetitiveTaskUpdateOne {
	_u.mutation.ResetOnceInDays()
	_u.mutation.SetOnceInDays(v)
	return _u
}

// SetNillableOnceInDays sets the "once_in_days" field if the given value is not nil.
func (_u *RepetitiveTaskUpdateOne) SetNillableOnceInDays(v *int) *RepetitiveTaskUpdateOne {
	if v != nil {
		_u.SetOnceInDays(*v)
	}
	return _u
}

// AddOnceInDays adds value to the "once_in_days" field.
func (_u *RepetitiveTaskUpdateOne) AddOnceInDays(v int) *RepetitiveTaskUpdateOne {
	_u.mutation.AddOnceInDays(v)
	return _u
}

// ClearOnceInDays clears the value of the "once_in_days" field.
func (_u *RepetitiveTaskUpdateOne) ClearOnceInDays() *RepetitiveTaskUpdateOne {
	_u.mutation.ClearOnceInDays()
	return _u
}

// SetOnceInWeeks sets the "once_in_weeks" field.
func (_u *RepetitiveTaskUpdateOne) SetOnceInWeeks(v int) *RepetitiveTaskUpdateOne {
	_u.mutation.ResetOnceInWeeks()
	_u.mutation.SetOnceInWeeks(v)
	return _u
}

// SetNillableOnceInWeeks sets the "once_in_weeks" field if the given value is not nil.
func (_u *RepetitiveTaskUpdateOne) SetNillableOnceInWeeks(v *int) *RepetitiveTaskUpdateOne {
	if v != nil {
		_u.SetOnceInWeeks(*v)
	}
	return _u
}

// AddOnceInWeeks adds value to the "once_in_weeks" field.
func (_u *RepetitiveTaskUpdateOne) AddOnceInWeeks(v int) *RepetitiveTaskUpdateOne {
	_u.mutation.AddOnceInWeeks(v)
	return _u
}

// ClearOnceInWeeks clears the value of the "once_in_weeks" field.
func (_u *RepetitiveTaskUpdateOne) ClearOnceInWeeks() *RepetitiveTaskUpdateOne {
	_u.mutation.ClearOnceInWeeks()
	return _u
}

// SetOnceInMonths sets the "once_in_months" field.
func (_u *RepetitiveTaskUpdateOne) SetOnceInMonths(v int) *RepetitiveTaskUpdateOne {
	_u.mutation.ResetOnceInMonths()
	_u.mutation.SetOnceInMonths(v)
	return _u
}

// SetNillableOnceInMonths sets the "once_in_months" field if the given value is not nil.
func (_u *RepetitiveTaskUpdateOne) SetNillableOnceInMonths(v *int) *RepetitiveTaskUpdateOne {
	if v != nil {
		_u.SetOnceInMonths(*v)
	}
	return _u
}

// AddOnceInMonths adds value to the "once_in_months" field.
func (_u *RepetitiveTaskUpdateOne) AddOnceInMonths(v int) *RepetitiveTaskUpdateOne {
	_u.mutation.AddOnceInMonths(v)
	return _u
}

// ClearOnceInMonths clears the value of the "once_in_months" field.
func (_u *RepetitiveTaskUpdateOne) ClearOnceInMonths() *RepetitiveTaskUpdateOne {
	_u.mutation.ClearOnceInMonths()
	return _u
}

// AddExecutionIDs adds the "executions" edge to the RepetitiveTaskExecution entity by IDs.
func (_u *RepetitiveTaskUpdateOne) AddExecutionIDs(ids ...int) *RepetitiveTaskUpdateOne {
	_u.mutation.AddExecutionIDs(ids...)
	return _u
}

// AddExecutions adds the "executions" edges to the RepetitiveTaskExecution entity.
func (_u *RepetitiveTaskUpdateOne) AddExecutions(v ...*RepetitiveTaskExecution) *RepetitiveTaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddExecutionIDs(ids...)
}

// Mutation returns the RepetitiveTaskMutation object of the builder.
func (_u *RepetitiveTaskUpdateOne) Mutation() *RepetitiveTaskMutation {
	return _u.mutation
}

// ClearExecutions clears all "executions" edges to the RepetitiveTaskExecution entity.
func (_u *RepetitiveTaskUpdateOne) ClearExecutions() *RepetitiveTaskUpdateOne {
	_u.mutation.ClearExecutions()
	return _u
}

// RemoveExecutionIDs removes the "executions" edge to RepetitiveTaskExecution entities by IDs.
func (_u *RepetitiveTaskUpdateOne) RemoveExecutionIDs(ids ...int) *RepetitiveTaskUpdateOne {
	_u.mutation.RemoveExecutionIDs(ids...)
	return _u
}

// RemoveExecutions removes "executions" edges to RepetitiveTaskExecution entities.
func (_u *RepetitiveTaskUpdateOne) RemoveExecutions(v ...*RepetitiveTaskExecution) *RepetitiveTaskUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveExecutionIDs(ids...)
}

// Where appends a list predicates to the RepetitiveTaskUpdate builder.
func (_u *RepetitiveTaskUpdateOne) Where(ps ...predicate.RepetitiveTask) *RepetitiveTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RepetitiveTaskUpdateOne) Select(field string, fields ...string) *RepetitiveTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RepetitiveTask entity.
func (_u *RepetitiveTaskUpdateOne) Save(ctx context.Context) (*RepetitiveTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RepetitiveTaskUpdateOne) SaveX(ctx context.Context) *RepetitiveTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RepetitiveTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RepetitiveTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RepetitiveTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := repetitivetask.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RepetitiveTask.description": %w`, err)}
		}
	}
	return nil
}

func (_u *RepetitiveTaskUpdateOne) sqlSave(ctx context.Context) (_node *RepetitiveTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(repetitivetask.Table, repetitivetask.Columns, sqlgraph.NewFieldSpec(repetitivetask.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RepetitiveTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, repetitivetask.FieldID)
		for _, f := range fields {
			if !repetitivetask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != repetitivetask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(repetitivetask.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(repetitivetask.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, repetitivetask.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Closed(); ok {
		_spec.SetField(repetitivetask.FieldClosed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(repetitivetask.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnceInDays(); ok {
		_spec.SetField(repetitivetask.FieldOnceInDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOnceInDays(); ok {
		_spec.AddField(repetitivetask.FieldOnceInDays, field.TypeInt, value)
	}
	if _u.mutation.OnceInDaysCleared() {
		_spec.ClearField(repetitivetask.FieldOnceInDays, field.TypeInt)
	}
	if value, ok := _u.mutation.OnceInWeeks(); ok {
		_spec.SetField(repetitivetask.FieldOnceInWeeks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOnceInWeeks(); ok {
		_spec.AddField(repetitivetask.FieldOnceInWeeks, field.TypeInt, value)
	}
	if _u.mutation.OnceInWeeksCleared() {
		_spec.ClearField(repetitivetask.FieldOnceInWeeks, field.TypeInt)
	}
	if value, ok := _u.mutation.OnceInMonths(); ok {
		_spec.SetField(repetitivetask.FieldOnceInMonths, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOnceInMonths(); ok {
		_spec.AddField(repetitivetask.FieldOnceInMonths, field.TypeInt, value)
	}
	if _u.mutation.OnceInMonthsCleared() {
		_spec.ClearField(repetitivetask.FieldOnceInMonths, field.TypeInt)
	}
	if _u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repetitivetask.ExecutionsTable,
			Columns: []string{repetitivetask.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repetitivetaskexecution.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedExecutionsIDs(); len(nodes) > 0 && !_u.mutation.ExecutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repetitivetask.ExecutionsTable,
			Columns: []string{repetitivetask.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repetitivetaskexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ExecutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   repetitivetask.ExecutionsTable,
			Columns: []string{repetitivetask.ExecutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(repetitivetaskexecution.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RepetitiveTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{repetitivetask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
