// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/containerchild"
	"arturgudiev/dashboard/ent/problem"
	"arturgudiev/dashboard/ent/schema"
	"arturgudiev/dashboard/ent/task"
	"arturgudiev/dashboard/ent/test"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	containerchildFields := schema.ContainerChild{}.Fields()
	_ = containerchildFields
	// containerchildDescParentID is the schema descriptor for parent_id field.
	containerchildDescParentID := containerchildFields[2].Descriptor()
	// containerchild.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	containerchild.ParentIDValidator = containerchildDescParentID.Validators[0].(func(int) error)
	// containerchildDescChildID is the schema descriptor for child_id field.
	containerchildDescChildID := containerchildFields[4].Descriptor()
	// containerchild.ChildIDValidator is a validator for the "child_id" field. It is called by the builders before save.
	containerchild.ChildIDValidator = containerchildDescChildID.Validators[0].(func(int) error)
	// containerchildDescChildOrder is the schema descriptor for child_order field.
	containerchildDescChildOrder := containerchildFields[5].Descriptor()
	// containerchild.DefaultChildOrder holds the default value on creation for the child_order field.
	containerchild.DefaultChildOrder = containerchildDescChildOrder.Default.(int)
	// containerchild.ChildOrderValidator is a validator for the "child_order" field. It is called by the builders before save.
	containerchild.ChildOrderValidator = containerchildDescChildOrder.Validators[0].(func(int) error)
	// containerchildDescParentOrder is the schema descriptor for parent_order field.
	containerchildDescParentOrder := containerchildFields[6].Descriptor()
	// containerchild.DefaultParentOrder holds the default value on creation for the parent_order field.
	containerchild.DefaultParentOrder = containerchildDescParentOrder.Default.(int)
	// containerchild.ParentOrderValidator is a validator for the "parent_order" field. It is called by the builders before save.
	containerchild.ParentOrderValidator = containerchildDescParentOrder.Validators[0].(func(int) error)
	// containerchildDescID is the schema descriptor for id field.
	containerchildDescID := containerchildFields[0].Descriptor()
	// containerchild.IDValidator is a validator for the "id" field. It is called by the builders before save.
	containerchild.IDValidator = containerchildDescID.Validators[0].(func(int) error)
	problemFields := schema.Problem{}.Fields()
	_ = problemFields
	// problemDescDescription is the schema descriptor for description field.
	problemDescDescription := problemFields[1].Descriptor()
	// problem.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	problem.DescriptionValidator = problemDescDescription.Validators[0].(func(string) error)
	// problemDescTags is the schema descriptor for tags field.
	problemDescTags := problemFields[2].Descriptor()
	// problem.DefaultTags holds the default value on creation for the tags field.
	problem.DefaultTags = problemDescTags.Default.([]string)
	// problemDescNotes is the schema descriptor for notes field.
	problemDescNotes := problemFields[3].Descriptor()
	// problem.DefaultNotes holds the default value on creation for the notes field.
	problem.DefaultNotes = problemDescNotes.Default.(string)
	// problemDescID is the schema descriptor for id field.
	problemDescID := problemFields[0].Descriptor()
	// problem.IDValidator is a validator for the "id" field. It is called by the builders before save.
	problem.IDValidator = problemDescID.Validators[0].(func(int) error)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescDescription is the schema descriptor for description field.
	taskDescDescription := taskFields[1].Descriptor()
	// task.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	task.DescriptionValidator = taskDescDescription.Validators[0].(func(string) error)
	// taskDescTags is the schema descriptor for tags field.
	taskDescTags := taskFields[2].Descriptor()
	// task.DefaultTags holds the default value on creation for the tags field.
	task.DefaultTags = taskDescTags.Default.([]string)
	// taskDescDone is the schema descriptor for done field.
	taskDescDone := taskFields[3].Descriptor()
	// task.DefaultDone holds the default value on creation for the done field.
	task.DefaultDone = taskDescDone.Default.(bool)
	// taskDescNotes is the schema descriptor for notes field.
	taskDescNotes := taskFields[4].Descriptor()
	// task.DefaultNotes holds the default value on creation for the notes field.
	task.DefaultNotes = taskDescNotes.Default.(string)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.IDValidator is a validator for the "id" field. It is called by the builders before save.
	task.IDValidator = taskDescID.Validators[0].(func(int) error)
	testFields := schema.Test{}.Fields()
	_ = testFields
	// testDescName is the schema descriptor for name field.
	testDescName := testFields[1].Descriptor()
	// test.NameValidator is a validator for the "name" field. It is called by the builders before save.
	test.NameValidator = testDescName.Validators[0].(func(string) error)
	// testDescTags is the schema descriptor for tags field.
	testDescTags := testFields[2].Descriptor()
	// test.DefaultTags holds the default value on creation for the tags field.
	test.DefaultTags = testDescTags.Default.([]string)
	// testDescID is the schema descriptor for id field.
	testDescID := testFields[0].Descriptor()
	// test.IDValidator is a validator for the "id" field. It is called by the builders before save.
	test.IDValidator = testDescID.Validators[0].(func(int) error)
}
