// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/predicate"
	"arturgudiev/dashboard/ent/schema"
	"arturgudiev/dashboard/ent/script"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ScriptUpdate is the builder for updating Script entities.
type ScriptUpdate struct {
	config
	hooks    []Hook
	mutation *ScriptMutation
}

// Where appends a list predicates to the ScriptUpdate builder.
func (_u *ScriptUpdate) Where(ps ...predicate.Script) *ScriptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ScriptUpdate) SetName(v string) *ScriptUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableName(v *string) *ScriptUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ScriptUpdate) SetCode(v string) *ScriptUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableCode(v *string) *ScriptUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScriptUpdate) SetDescription(v string) *ScriptUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableDescription(v *string) *ScriptUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetParams sets the "params" field.
func (_u *ScriptUpdate) SetParams(v []schema.ScriptParam) *ScriptUpdate {
	_u.mutation.SetParams(v)
	return _u
}

// AppendParams appends value to the "params" field.
func (_u *ScriptUpdate) AppendParams(v []schema.ScriptParam) *ScriptUpdate {
	_u.mutation.AppendParams(v)
	return _u
}

// ClearParams clears the value of the "params" field.
func (_u *ScriptUpdate) ClearParams() *ScriptUpdate {
	_u.mutation.ClearParams()
	return _u
}

// SetContainerType sets the "container_type" field.
func (_u *ScriptUpdate) SetContainerType(v schema.ContainerType) *ScriptUpdate {
	_u.mutation.SetContainerType(v)
	return _u
}

// SetNillableContainerType sets the "container_type" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableContainerType(v *schema.ContainerType) *ScriptUpdate {
	if v != nil {
		_u.SetContainerType(*v)
	}
	return _u
}

// ClearContainerType clears the value of the "container_type" field.
func (_u *ScriptUpdate) ClearContainerType() *ScriptUpdate {
	_u.mutation.ClearContainerType()
	return _u
}

// SetContainerID sets the "container_id" field.
func (_u *ScriptUpdate) SetContainerID(v int) *ScriptUpdate {
	_u.mutation.ResetContainerID()
	_u.mutation.SetContainerID(v)
	return _u
}

// SetNillableContainerID sets the "container_id" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableContainerID(v *int) *ScriptUpdate {
	if v != nil {
		_u.SetContainerID(*v)
	}
	return _u
}

// AddContainerID adds value to the "container_id" field.
func (_u *ScriptUpdate) AddContainerID(v int) *ScriptUpdate {
	_u.mutation.AddContainerID(v)
	return _u
}

// ClearContainerID clears the value of the "container_id" field.
func (_u *ScriptUpdate) ClearContainerID() *ScriptUpdate {
	_u.mutation.ClearContainerID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptUpdate) SetUpdatedAt(v time.Time) *ScriptUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ScriptMutation object of the builder.
func (_u *ScriptUpdate) Mutation() *ScriptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScriptUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScriptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := script.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := script.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Script.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContainerType(); ok {
		if err := script.ContainerTypeValidator(v); err != nil {
			return &ValidationError{Name: "container_type", err: fmt.Errorf(`ent: validator failed for field "Script.container_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContainerID(); ok {
		if err := script.ContainerIDValidator(v); err != nil {
			return &ValidationError{Name: "container_id", err: fmt.Errorf(`ent: validator failed for field "Script.container_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ScriptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(script.Table, script.Columns, sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(script.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(script.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Params(); ok {
		_spec.SetField(script.FieldParams, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParams(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, script.FieldParams, value)
		})
	}
	if _u.mutation.ParamsCleared() {
		_spec.ClearField(script.FieldParams, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContainerType(); ok {
		_spec.SetField(script.FieldContainerType, field.TypeEnum, value)
	}
	if _u.mutation.ContainerTypeCleared() {
		_spec.ClearField(script.FieldContainerType, field.TypeEnum)
	}
	if value, ok := _u.mutation.ContainerID(); ok {
		_spec.SetField(script.FieldContainerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContainerID(); ok {
		_spec.AddField(script.FieldContainerID, field.TypeInt, value)
	}
	if _u.mutation.ContainerIDCleared() {
		_spec.ClearField(script.FieldContainerID, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(script.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{script.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScriptUpdateOne is the builder for updating a single Script entity.
type ScriptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ScriptMutation
}

// SetName sets the "name" field.
func (_u *ScriptUpdateOne) SetName(v string) *ScriptUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableName(v *string) *ScriptUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *ScriptUpdateOne) SetCode(v string) *ScriptUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableCode(v *string) *ScriptUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScriptUpdateOne) SetDescription(v string) *ScriptUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableDescription(v *string) *ScriptUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetParams sets the "params" field.
func (_u *ScriptUpdateOne) SetParams(v []schema.ScriptParam) *ScriptUpdateOne {
	_u.mutation.SetParams(v)
	return _u
}

// AppendParams appends value to the "params" field.
func (_u *ScriptUpdateOne) AppendParams(v []schema.ScriptParam) *ScriptUpdateOne {
	_u.mutation.AppendParams(v)
	return _u
}

// ClearParams clears the value of the "params" field.
func (_u *ScriptUpdateOne) ClearParams() *ScriptUpdateOne {
	_u.mutation.ClearParams()
	return _u
}

// SetContainerType sets the "container_type" field.
func (_u *ScriptUpdateOne) SetContainerType(v schema.ContainerType) *ScriptUpdateOne {
	_u.mutation.SetContainerType(v)
	return _u
}

// SetNillableContainerType sets the "container_type" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableContainerType(v *schema.ContainerType) *ScriptUpdateOne {
	if v != nil {
		_u.SetContainerType(*v)
	}
	return _u
}

// ClearContainerType clears the value of the "container_type" field.
func (_u *ScriptUpdateOne) ClearContainerType() *ScriptUpdateOne {
	_u.mutation.ClearContainerType()
	return _u
}

// SetContainerID sets the "container_id" field.
func (_u *ScriptUpdateOne) SetContainerID(v int) *ScriptUpdateOne {
	_u.mutation.ResetContainerID()
	_u.mutation.SetContainerID(v)
	return _u
}

// SetNillableContainerID sets the "container_id" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableContainerID(v *int) *ScriptUpdateOne {
	if v != nil {
		_u.SetContainerID(*v)
	}
	return _u
}

// AddContainerID adds value to the "container_id" field.
func (_u *ScriptUpdateOne) AddContainerID(v int) *ScriptUpdateOne {
	_u.mutation.AddContainerID(v)
	return _u
}

// ClearContainerID clears the value of the "container_id" field.
func (_u *ScriptUpdateOne) ClearContainerID() *ScriptUpdateOne {
	_u.mutation.ClearContainerID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ScriptUpdateOne) SetUpdatedAt(v time.Time) *ScriptUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ScriptMutation object of the builder.
func (_u *ScriptUpdateOne) Mutation() *ScriptMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScriptUpdate builder.
func (_u *ScriptUpdateOne) Where(ps ...predicate.Script) *ScriptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScriptUpdateOne) Select(field string, fields ...string) *ScriptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Script entity.
func (_u *ScriptUpdateOne) Save(ctx context.Context) (*Script, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptUpdateOne) SaveX(ctx context.Context) *Script {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScriptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ScriptUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := script.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := script.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Script.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContainerType(); ok {
		if err := script.ContainerTypeValidator(v); err != nil {
			return &ValidationError{Name: "container_type", err: fmt.Errorf(`ent: validator failed for field "Script.container_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContainerID(); ok {
		if err := script.ContainerIDValidator(v); err != nil {
			return &ValidationError{Name: "container_id", err: fmt.Errorf(`ent: validator failed for field "Script.container_id": %w`, err)}
		}
	}
	return nil
}

func (_u *ScriptUpdateOne) sqlSave(ctx context.Context) (_node *Script, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(script.Table, script.Columns, sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Script.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, script.FieldID)
		for _, f := range fields {
			if !script.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != script.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(script.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(script.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Params(); ok {
		_spec.SetField(script.FieldParams, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedParams(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, script.FieldParams, value)
		})
	}
	if _u.mutation.ParamsCleared() {
		_spec.ClearField(script.FieldParams, field.TypeJSON)
	}
	if value, ok := _u.mutation.ContainerType(); ok {
		_spec.SetField(script.FieldContainerType, field.TypeEnum, value)
	}
	if _u.mutation.ContainerTypeCleared() {
		_spec.ClearField(script.FieldContainerType, field.TypeEnum)
	}
	if value, ok := _u.mutation.ContainerID(); ok {
		_spec.SetField(script.FieldContainerID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedContainerID(); ok {
		_spec.AddField(script.FieldContainerID, field.TypeInt, value)
	}
	if _u.mutation.ContainerIDCleared() {
		_spec.ClearField(script.FieldContainerID, field.TypeInt)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(script.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Script{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{script.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
