// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/schema"
	"arturgudiev/dashboard/ent/script"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ScriptCreate is the builder for creating a Script entity.
type ScriptCreate struct {
	config
	mutation *ScriptMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *ScriptCreate) SetName(v string) *ScriptCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *ScriptCreate) SetCode(v string) *ScriptCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ScriptCreate) SetDescription(v string) *ScriptCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableDescription(v *string) *ScriptCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetParams sets the "params" field.
func (_c *ScriptCreate) SetParams(v []schema.ScriptParam) *ScriptCreate {
	_c.mutation.SetParams(v)
	return _c
}

// SetContainerType sets the "container_type" field.
func (_c *ScriptCreate) SetContainerType(v schema.ContainerType) *ScriptCreate {
	_c.mutation.SetContainerType(v)
	return _c
}

// SetNillableContainerType sets the "container_type" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableContainerType(v *schema.ContainerType) *ScriptCreate {
	if v != nil {
		_c.SetContainerType(*v)
	}
	return _c
}

// SetContainerID sets the "container_id" field.
func (_c *ScriptCreate) SetContainerID(v int) *ScriptCreate {
	_c.mutation.SetContainerID(v)
	return _c
}

// SetNillableContainerID sets the "container_id" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableContainerID(v *int) *ScriptCreate {
	if v != nil {
		_c.SetContainerID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ScriptCreate) SetCreatedAt(v time.Time) *ScriptCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableCreatedAt(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ScriptCreate) SetUpdatedAt(v time.Time) *ScriptCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableUpdatedAt(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScriptCreate) SetID(v int) *ScriptCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ScriptMutation object of the builder.
func (_c *ScriptCreate) Mutation() *ScriptMutation {
	return _c.mutation
}

// Save creates the Script in the database.
func (_c *ScriptCreate) Save(ctx context.Context) (*Script, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScriptCreate) SaveX(ctx context.Context) *Script {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScriptCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := script.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := script.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := script.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScriptCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Script.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Script.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := script.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Script.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Script.description"`)}
	}
	if v, ok := _c.mutation.ContainerType(); ok {
		if err := script.ContainerTypeValidator(v); err != nil {
			return &ValidationError{Name: "container_type", err: fmt.Errorf(`ent: validator failed for field "Script.container_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ContainerID(); ok {
		if err := script.ContainerIDValidator(v); err != nil {
			return &ValidationError{Name: "container_id", err: fmt.Errorf(`ent: validator failed for field "Script.container_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Script.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Script.updated_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := script.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Script.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ScriptCreate) sqlSave(ctx context.Context) (*Script, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScriptCreate) createSpec() (*Script, *sqlgraph.CreateSpec) {
	var (
		_node = &Script{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(script.Table, sqlgraph.NewFieldSpec(script.FieldID, field.TypeInt))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(script.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(script.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Params(); ok {
		_spec.SetField(script.FieldParams, field.TypeJSON, value)
		_node.Params = value
	}
	if value, ok := _c.mutation.ContainerType(); ok {
		_spec.SetField(script.FieldContainerType, field.TypeEnum, value)
		_node.ContainerType = &value
	}
	if value, ok := _c.mutation.ContainerID(); ok {
		_spec.SetField(script.FieldContainerID, field.TypeInt, value)
		_node.ContainerID = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(script.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(script.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ScriptCreateBulk is the builder for creating many Script entities in bulk.
type ScriptCreateBulk struct {
	config
	err      error
	builders []*ScriptCreate
}

// Save creates the Script entities in the database.
func (_c *ScriptCreateBulk) Save(ctx context.Context) ([]*Script, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Script, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScriptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScriptCreateBulk) SaveX(ctx context.Context) []*Script {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
