// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/predicate"
	"arturgudiev/dashboard/ent/state"
	"arturgudiev/dashboard/ent/staterequirement"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// StateUpdate is the builder for updating State entities.
type StateUpdate struct {
	config
	hooks    []Hook
	mutation *StateMutation
}

// Where appends a list predicates to the StateUpdate builder.
func (_u *StateUpdate) Where(ps ...predicate.State) *StateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDescription sets the "description" field.
func (_u *StateUpdate) SetDescription(v string) *StateUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StateUpdate) SetNillableDescription(v *string) *StateUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *StateUpdate) SetTags(v []string) *StateUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *StateUpdate) AppendTags(v []string) *StateUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// SetClosed sets the "closed" field.
func (_u *StateUpdate) SetClosed(v bool) *StateUpdate {
	_u.mutation.SetClosed(v)
	return _u
}

// SetNillableClosed sets the "closed" field if the given value is not nil.
func (_u *StateUpdate) SetNillableClosed(v *bool) *StateUpdate {
	if v != nil {
		_u.SetClosed(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *StateUpdate) SetNotes(v string) *StateUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *StateUpdate) SetNillableNotes(v *string) *StateUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// AddRequirementIDs adds the "requirements" edge to the StateRequirement entity by IDs.
func (_u *StateUpdate) AddRequirementIDs(ids ...int) *StateUpdate {
	_u.mutation.AddRequirementIDs(ids...)
	return _u
}

// AddRequirements adds the "requirements" edges to the StateRequirement entity.
func (_u *StateUpdate) AddRequirements(v ...*StateRequirement) *StateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequirementIDs(ids...)
}

// Mutation returns the StateMutation object of the builder.
func (_u *StateUpdate) Mutation() *StateMutation {
	return _u.mutation
}

// ClearRequirements clears all "requirements" edges to the StateRequirement entity.
func (_u *StateUpdate) ClearRequirements() *StateUpdate {
	_u.mutation.ClearRequirements()
	return _u
}

// RemoveRequirementIDs removes the "requirements" edge to StateRequirement entities by IDs.
func (_u *StateUpdate) RemoveRequirementIDs(ids ...int) *StateUpdate {
	_u.mutation.RemoveRequirementIDs(ids...)
	return _u
}

// RemoveRequirements removes "requirements" edges to StateRequirement entities.
func (_u *StateUpdate) RemoveRequirements(v ...*StateRequirement) *StateUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequirementIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StateUpdate) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := state.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "State.description": %w`, err)}
		}
	}
	return nil
}

func (_u *StateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(state.Table, state.Columns, sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(state.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(state.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, state.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Closed(); ok {
		_spec.SetField(state.FieldClosed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(state.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.RequirementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   state.RequirementsTable,
			Columns: []string{state.RequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequirementsIDs(); len(nodes) > 0 && !_u.mutation.RequirementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   state.RequirementsTable,
			Columns: []string{state.RequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequirementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   state.RequirementsTable,
			Columns: []string{state.RequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{state.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StateUpdateOne is the builder for updating a single State entity.
type StateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StateMutation
}

// SetDescription sets the "description" field.
func (_u *StateUpdateOne) SetDescription(v string) *StateUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableDescription(v *string) *StateUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *StateUpdateOne) SetTags(v []string) *StateUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *StateUpdateOne) AppendTags(v []string) *StateUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// SetClosed sets the "closed" field.
func (_u *StateUpdateOne) SetClosed(v bool) *StateUpdateOne {
	_u.mutation.SetClosed(v)
	return _u
}

// SetNillableClosed sets the "closed" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableClosed(v *bool) *StateUpdateOne {
	if v != nil {
		_u.SetClosed(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *StateUpdateOne) SetNotes(v string) *StateUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *StateUpdateOne) SetNillableNotes(v *string) *StateUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// AddRequirementIDs adds the "requirements" edge to the StateRequirement entity by IDs.
func (_u *StateUpdateOne) AddRequirementIDs(ids ...int) *StateUpdateOne {
	_u.mutation.AddRequirementIDs(ids...)
	return _u
}

// AddRequirements adds the "requirements" edges to the StateRequirement entity.
func (_u *StateUpdateOne) AddRequirements(v ...*StateRequirement) *StateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequirementIDs(ids...)
}

// Mutation returns the StateMutation object of the builder.
func (_u *StateUpdateOne) Mutation() *StateMutation {
	return _u.mutation
}

// ClearRequirements clears all "requirements" edges to the StateRequirement entity.
func (_u *StateUpdateOne) ClearRequirements() *StateUpdateOne {
	_u.mutation.ClearRequirements()
	return _u
}

// RemoveRequirementIDs removes the "requirements" edge to StateRequirement entities by IDs.
func (_u *StateUpdateOne) RemoveRequirementIDs(ids ...int) *StateUpdateOne {
	_u.mutation.RemoveRequirementIDs(ids...)
	return _u
}

// RemoveRequirements removes "requirements" edges to StateRequirement entities.
func (_u *StateUpdateOne) RemoveRequirements(v ...*StateRequirement) *StateUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequirementIDs(ids...)
}

// Where appends a list predicates to the StateUpdate builder.
func (_u *StateUpdateOne) Where(ps ...predicate.State) *StateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StateUpdateOne) Select(field string, fields ...string) *StateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated State entity.
func (_u *StateUpdateOne) Save(ctx context.Context) (*State, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StateUpdateOne) SaveX(ctx context.Context) *State {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StateUpdateOne) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := state.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "State.description": %w`, err)}
		}
	}
	return nil
}

func (_u *StateUpdateOne) sqlSave(ctx context.Context) (_node *State, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(state.Table, state.Columns, sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "State.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, state.FieldID)
		for _, f := range fields {
			if !state.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != state.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(state.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(state.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, state.FieldTags, value)
		})
	}
	if value, ok := _u.mutation.Closed(); ok {
		_spec.SetField(state.FieldClosed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(state.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.RequirementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   state.RequirementsTable,
			Columns: []string{state.RequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirement.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequirementsIDs(); len(nodes) > 0 && !_u.mutation.RequirementsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   state.RequirementsTable,
			Columns: []string{state.RequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequirementsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   state.RequirementsTable,
			Columns: []string{state.RequirementsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirement.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &State{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{state.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
