// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/predicate"
	"arturgudiev/dashboard/ent/state"
	"arturgudiev/dashboard/ent/staterequirement"
	"arturgudiev/dashboard/ent/staterequirementcheck"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StateRequirementUpdate is the builder for updating StateRequirement entities.
type StateRequirementUpdate struct {
	config
	hooks    []Hook
	mutation *StateRequirementMutation
}

// Where appends a list predicates to the StateRequirementUpdate builder.
func (_u *StateRequirementUpdate) Where(ps ...predicate.StateRequirement) *StateRequirementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDescription sets the "description" field.
func (_u *StateRequirementUpdate) SetDescription(v string) *StateRequirementUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StateRequirementUpdate) SetNillableDescription(v *string) *StateRequirementUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStateID sets the "state_id" field.
func (_u *StateRequirementUpdate) SetStateID(v int) *StateRequirementUpdate {
	_u.mutation.SetStateID(v)
	return _u
}

// SetNillableStateID sets the "state_id" field if the given value is not nil.
func (_u *StateRequirementUpdate) SetNillableStateID(v *int) *StateRequirementUpdate {
	if v != nil {
		_u.SetStateID(*v)
	}
	return _u
}

// SetOnceInDays sets the "once_in_days" field.
func (_u *StateRequirementUpdate) SetOnceInDays(v int) *StateRequirementUpdate {
	_u.mutation.ResetOnceInDays()
	_u.mutation.SetOnceInDays(v)
	return _u
}

// SetNillableOnceInDays sets the "once_in_days" field if the given value is not nil.
func (_u *StateRequirementUpdate) SetNillableOnceInDays(v *int) *StateRequirementUpdate {
	if v != nil {
		_u.SetOnceInDays(*v)
	}
	return _u
}

// AddOnceInDays adds value to the "once_in_days" field.
func (_u *StateRequirementUpdate) AddOnceInDays(v int) *StateRequirementUpdate {
	_u.mutation.AddOnceInDays(v)
	return _u
}

// ClearOnceInDays clears the value of the "once_in_days" field.
func (_u *StateRequirementUpdate) ClearOnceInDays() *StateRequirementUpdate {
	_u.mutation.ClearOnceInDays()
	return _u
}

// SetState sets the "state" edge to the State entity.
func (_u *StateRequirementUpdate) SetState(v *State) *StateRequirementUpdate {
	return _u.SetStateID(v.ID)
}

// AddCheckIDs adds the "checks" edge to the StateRequirementCheck entity by IDs.
func (_u *StateRequirementUpdate) AddCheckIDs(ids ...int) *StateRequirementUpdate {
	_u.mutation.AddCheckIDs(ids...)
	return _u
}

// AddChecks adds the "checks" edges to the StateRequirementCheck entity.
func (_u *StateRequirementUpdate) AddChecks(v ...*StateRequirementCheck) *StateRequirementUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckIDs(ids...)
}

// Mutation returns the StateRequirementMutation object of the builder.
func (_u *StateRequirementUpdate) Mutation() *StateRequirementMutation {
	return _u.mutation
}

// ClearState clears the "state" edge to the State entity.
func (_u *StateRequirementUpdate) ClearState() *StateRequirementUpdate {
	_u.mutation.ClearState()
	return _u
}

// ClearChecks clears all "checks" edges to the StateRequirementCheck entity.
func (_u *StateRequirementUpdate) ClearChecks() *StateRequirementUpdate {
	_u.mutation.ClearChecks()
	return _u
}

// RemoveCheckIDs removes the "checks" edge to StateRequirementCheck entities by IDs.
func (_u *StateRequirementUpdate) RemoveCheckIDs(ids ...int) *StateRequirementUpdate {
	_u.mutation.RemoveCheckIDs(ids...)
	return _u
}

// RemoveChecks removes "checks" edges to StateRequirementCheck entities.
func (_u *StateRequirementUpdate) RemoveChecks(v ...*StateRequirementCheck) *StateRequirementUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StateRequirementUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StateRequirementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StateRequirementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StateRequirementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StateRequirementUpdate) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := staterequirement.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "StateRequirement.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StateID(); ok {
		if err := staterequirement.StateIDValidator(v); err != nil {
			return &ValidationError{Name: "state_id", err: fmt.Errorf(`ent: validator failed for field "StateRequirement.state_id": %w`, err)}
		}
	}
	if _u.mutation.StateCleared() && len(_u.mutation.StateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StateRequirement.state"`)
	}
	return nil
}

func (_u *StateRequirementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(staterequirement.Table, staterequirement.Columns, sqlgraph.NewFieldSpec(staterequirement.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(staterequirement.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnceInDays(); ok {
		_spec.SetField(staterequirement.FieldOnceInDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOnceInDays(); ok {
		_spec.AddField(staterequirement.FieldOnceInDays, field.TypeInt, value)
	}
	if _u.mutation.OnceInDaysCleared() {
		_spec.ClearField(staterequirement.FieldOnceInDays, field.TypeInt)
	}
	if _u.mutation.StateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   staterequirement.StateTable,
			Columns: []string{staterequirement.StateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   staterequirement.StateTable,
			Columns: []string{staterequirement.StateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staterequirement.ChecksTable,
			Columns: []string{staterequirement.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirementcheck.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChecksIDs(); len(nodes) > 0 && !_u.mutation.ChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staterequirement.ChecksTable,
			Columns: []string{staterequirement.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirementcheck.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staterequirement.ChecksTable,
			Columns: []string{staterequirement.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirementcheck.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{staterequirement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StateRequirementUpdateOne is the builder for updating a single StateRequirement entity.
type StateRequirementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StateRequirementMutation
}

// SetDescription sets the "description" field.
func (_u *StateRequirementUpdateOne) SetDescription(v string) *StateRequirementUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *StateRequirementUpdateOne) SetNillableDescription(v *string) *StateRequirementUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStateID sets the "state_id" field.
func (_u *StateRequirementUpdateOne) SetStateID(v int) *StateRequirementUpdateOne {
	_u.mutation.SetStateID(v)
	return _u
}

// SetNillableStateID sets the "state_id" field if the given value is not nil.
func (_u *StateRequirementUpdateOne) SetNillableStateID(v *int) *StateRequirementUpdateOne {
	if v != nil {
		_u.SetStateID(*v)
	}
	return _u
}

// SetOnceInDays sets the "once_in_days" field.
func (_u *StateRequirementUpdateOne) SetOnceInDays(v int) *StateRequirementUpdateOne {
	_u.mutation.ResetOnceInDays()
	_u.mutation.SetOnceInDays(v)
	return _u
}

// SetNillableOnceInDays sets the "once_in_days" field if the given value is not nil.
func (_u *StateRequirementUpdateOne) SetNillableOnceInDays(v *int) *StateRequirementUpdateOne {
	if v != nil {
		_u.SetOnceInDays(*v)
	}
	return _u
}

// AddOnceInDays adds value to the "once_in_days" field.
func (_u *StateRequirementUpdateOne) AddOnceInDays(v int) *StateRequirementUpdateOne {
	_u.mutation.AddOnceInDays(v)
	return _u
}

// ClearOnceInDays clears the value of the "once_in_days" field.
func (_u *StateRequirementUpdateOne) ClearOnceInDays() *StateRequirementUpdateOne {
	_u.mutation.ClearOnceInDays()
	return _u
}

// SetState sets the "state" edge to the State entity.
func (_u *StateRequirementUpdateOne) SetState(v *State) *StateRequirementUpdateOne {
	return _u.SetStateID(v.ID)
}

// AddCheckIDs adds the "checks" edge to the StateRequirementCheck entity by IDs.
func (_u *StateRequirementUpdateOne) AddCheckIDs(ids ...int) *StateRequirementUpdateOne {
	_u.mutation.AddCheckIDs(ids...)
	return _u
}

// AddChecks adds the "checks" edges to the StateRequirementCheck entity.
func (_u *StateRequirementUpdateOne) AddChecks(v ...*StateRequirementCheck) *StateRequirementUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCheckIDs(ids...)
}

// Mutation returns the StateRequirementMutation object of the builder.
func (_u *StateRequirementUpdateOne) Mutation() *StateRequirementMutation {
	return _u.mutation
}

// ClearState clears the "state" edge to the State entity.
func (_u *StateRequirementUpdateOne) ClearState() *StateRequirementUpdateOne {
	_u.mutation.ClearState()
	return _u
}

// ClearChecks clears all "checks" edges to the StateRequirementCheck entity.
func (_u *StateRequirementUpdateOne) ClearChecks() *StateRequirementUpdateOne {
	_u.mutation.ClearChecks()
	return _u
}

// RemoveCheckIDs removes the "checks" edge to StateRequirementCheck entities by IDs.
func (_u *StateRequirementUpdateOne) RemoveCheckIDs(ids ...int) *StateRequirementUpdateOne {
	_u.mutation.RemoveCheckIDs(ids...)
	return _u
}

// RemoveChecks removes "checks" edges to StateRequirementCheck entities.
func (_u *StateRequirementUpdateOne) RemoveChecks(v ...*StateRequirementCheck) *StateRequirementUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCheckIDs(ids...)
}

// Where appends a list predicates to the StateRequirementUpdate builder.
func (_u *StateRequirementUpdateOne) Where(ps ...predicate.StateRequirement) *StateRequirementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StateRequirementUpdateOne) Select(field string, fields ...string) *StateRequirementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StateRequirement entity.
func (_u *StateRequirementUpdateOne) Save(ctx context.Context) (*StateRequirement, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StateRequirementUpdateOne) SaveX(ctx context.Context) *StateRequirement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StateRequirementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StateRequirementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StateRequirementUpdateOne) check() error {
	if v, ok := _u.mutation.Description(); ok {
		if err := staterequirement.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "StateRequirement.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StateID(); ok {
		if err := staterequirement.StateIDValidator(v); err != nil {
			return &ValidationError{Name: "state_id", err: fmt.Errorf(`ent: validator failed for field "StateRequirement.state_id": %w`, err)}
		}
	}
	if _u.mutation.StateCleared() && len(_u.mutation.StateIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StateRequirement.state"`)
	}
	return nil
}

func (_u *StateRequirementUpdateOne) sqlSave(ctx context.Context) (_node *StateRequirement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(staterequirement.Table, staterequirement.Columns, sqlgraph.NewFieldSpec(staterequirement.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StateRequirement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, staterequirement.FieldID)
		for _, f := range fields {
			if !staterequirement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != staterequirement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(staterequirement.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.OnceInDays(); ok {
		_spec.SetField(staterequirement.FieldOnceInDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOnceInDays(); ok {
		_spec.AddField(staterequirement.FieldOnceInDays, field.TypeInt, value)
	}
	if _u.mutation.OnceInDaysCleared() {
		_spec.ClearField(staterequirement.FieldOnceInDays, field.TypeInt)
	}
	if _u.mutation.StateCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   staterequirement.StateTable,
			Columns: []string{staterequirement.StateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   staterequirement.StateTable,
			Columns: []string{staterequirement.StateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(state.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staterequirement.ChecksTable,
			Columns: []string{staterequirement.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirementcheck.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChecksIDs(); len(nodes) > 0 && !_u.mutation.ChecksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staterequirement.ChecksTable,
			Columns: []string{staterequirement.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirementcheck.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staterequirement.ChecksTable,
			Columns: []string{staterequirement.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(staterequirementcheck.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StateRequirement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{staterequirement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
