// Code generated by ent, DO NOT EDIT.

package ent

import (
	"arturgudiev/dashboard/ent/containervariables"
	"arturgudiev/dashboard/ent/predicate"
	"arturgudiev/dashboard/ent/variablesstack"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// VariablesStackQuery is the builder for querying VariablesStack entities.
type VariablesStackQuery struct {
	config
	ctx                    *QueryContext
	order                  []variablesstack.OrderOption
	inters                 []Interceptor
	predicates             []predicate.VariablesStack
	withContainerVariables *ContainerVariablesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VariablesStackQuery builder.
func (_q *VariablesStackQuery) Where(ps ...predicate.VariablesStack) *VariablesStackQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VariablesStackQuery) Limit(limit int) *VariablesStackQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VariablesStackQuery) Offset(offset int) *VariablesStackQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VariablesStackQuery) Unique(unique bool) *VariablesStackQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VariablesStackQuery) Order(o ...variablesstack.OrderOption) *VariablesStackQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryContainerVariables chains the current query on the "container_variables" edge.
func (_q *VariablesStackQuery) QueryContainerVariables() *ContainerVariablesQuery {
	query := (&ContainerVariablesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(variablesstack.Table, variablesstack.FieldID, selector),
			sqlgraph.To(containervariables.Table, containervariables.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, variablesstack.ContainerVariablesTable, variablesstack.ContainerVariablesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first VariablesStack entity from the query.
// Returns a *NotFoundError when no VariablesStack was found.
func (_q *VariablesStackQuery) First(ctx context.Context) (*VariablesStack, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{variablesstack.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VariablesStackQuery) FirstX(ctx context.Context) *VariablesStack {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first VariablesStack ID from the query.
// Returns a *NotFoundError when no VariablesStack ID was found.
func (_q *VariablesStackQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{variablesstack.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VariablesStackQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single VariablesStack entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one VariablesStack entity is found.
// Returns a *NotFoundError when no VariablesStack entities are found.
func (_q *VariablesStackQuery) Only(ctx context.Context) (*VariablesStack, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{variablesstack.Label}
	default:
		return nil, &NotSingularError{variablesstack.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VariablesStackQuery) OnlyX(ctx context.Context) *VariablesStack {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only VariablesStack ID in the query.
// Returns a *NotSingularError when more than one VariablesStack ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VariablesStackQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{variablesstack.Label}
	default:
		err = &NotSingularError{variablesstack.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VariablesStackQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of VariablesStacks.
func (_q *VariablesStackQuery) All(ctx context.Context) ([]*VariablesStack, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*VariablesStack, *VariablesStackQuery]()
	return withInterceptors[[]*VariablesStack](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VariablesStackQuery) AllX(ctx context.Context) []*VariablesStack {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of VariablesStack IDs.
func (_q *VariablesStackQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(variablesstack.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VariablesStackQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VariablesStackQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VariablesStackQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VariablesStackQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VariablesStackQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VariablesStackQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VariablesStackQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VariablesStackQuery) Clone() *VariablesStackQuery {
	if _q == nil {
		return nil
	}
	return &VariablesStackQuery{
		config:                 _q.config,
		ctx:                    _q.ctx.Clone(),
		order:                  append([]variablesstack.OrderOption{}, _q.order...),
		inters:                 append([]Interceptor{}, _q.inters...),
		predicates:             append([]predicate.VariablesStack{}, _q.predicates...),
		withContainerVariables: _q.withContainerVariables.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithContainerVariables tells the query-builder to eager-load the nodes that are connected to
// the "container_variables" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VariablesStackQuery) WithContainerVariables(opts ...func(*ContainerVariablesQuery)) *VariablesStackQuery {
	query := (&ContainerVariablesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withContainerVariables = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ContainerType schema.ContainerType `json:"container_type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.VariablesStack.Query().
//		GroupBy(variablesstack.FieldContainerType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VariablesStackQuery) GroupBy(field string, fields ...string) *VariablesStackGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VariablesStackGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = variablesstack.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ContainerType schema.ContainerType `json:"container_type,omitempty"`
//	}
//
//	client.VariablesStack.Query().
//		Select(variablesstack.FieldContainerType).
//		Scan(ctx, &v)
func (_q *VariablesStackQuery) Select(fields ...string) *VariablesStackSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VariablesStackSelect{VariablesStackQuery: _q}
	sbuild.label = variablesstack.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VariablesStackSelect configured with the given aggregations.
func (_q *VariablesStackQuery) Aggregate(fns ...AggregateFunc) *VariablesStackSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VariablesStackQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !variablesstack.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VariablesStackQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*VariablesStack, error) {
	var (
		nodes       = []*VariablesStack{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withContainerVariables != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*VariablesStack).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &VariablesStack{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withContainerVariables; query != nil {
		if err := _q.loadContainerVariables(ctx, query, nodes,
			func(n *VariablesStack) { n.Edges.ContainerVariables = []*ContainerVariables{} },
			func(n *VariablesStack, e *ContainerVariables) {
				n.Edges.ContainerVariables = append(n.Edges.ContainerVariables, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VariablesStackQuery) loadContainerVariables(ctx context.Context, query *ContainerVariablesQuery, nodes []*VariablesStack, init func(*VariablesStack), assign func(*VariablesStack, *ContainerVariables)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*VariablesStack)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(containervariables.FieldVariablesStackID)
	}
	query.Where(predicate.ContainerVariables(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(variablesstack.ContainerVariablesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VariablesStackID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "variables_stack_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *VariablesStackQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VariablesStackQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(variablesstack.Table, variablesstack.Columns, sqlgraph.NewFieldSpec(variablesstack.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, variablesstack.FieldID)
		for i := range fields {
			if fields[i] != variablesstack.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VariablesStackQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(variablesstack.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = variablesstack.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VariablesStackGroupBy is the group-by builder for VariablesStack entities.
type VariablesStackGroupBy struct {
	selector
	build *VariablesStackQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VariablesStackGroupBy) Aggregate(fns ...AggregateFunc) *VariablesStackGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VariablesStackGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VariablesStackQuery, *VariablesStackGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VariablesStackGroupBy) sqlScan(ctx context.Context, root *VariablesStackQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VariablesStackSelect is the builder for selecting fields of VariablesStack entities.
type VariablesStackSelect struct {
	*VariablesStackQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VariablesStackSelect) Aggregate(fns ...AggregateFunc) *VariablesStackSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VariablesStackSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VariablesStackQuery, *VariablesStackSelect](ctx, _s.VariablesStackQuery, _s, _s.inters, v)
}

func (_s *VariablesStackSelect) sqlScan(ctx context.Context, root *VariablesStackQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
