// Code generated by ent, DO NOT EDIT.

package containercheck

import (
	"arturgudiev/dashboard/ent/predicate"
	"arturgudiev/dashboard/ent/schema"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldLTE(FieldID, id))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldEQ(FieldDescription, v))
}

// ContainerID applies equality check predicate on the "container_id" field. It's identical to ContainerIDEQ.
func ContainerID(v int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldEQ(FieldContainerID, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldContainsFold(FieldDescription, v))
}

// ContainerTypeEQ applies the EQ predicate on the "container_type" field.
func ContainerTypeEQ(v schema.ContainerType) predicate.ContainerCheck {
	vc := v
	return predicate.ContainerCheck(sql.FieldEQ(FieldContainerType, vc))
}

// ContainerTypeNEQ applies the NEQ predicate on the "container_type" field.
func ContainerTypeNEQ(v schema.ContainerType) predicate.ContainerCheck {
	vc := v
	return predicate.ContainerCheck(sql.FieldNEQ(FieldContainerType, vc))
}

// ContainerTypeIn applies the In predicate on the "container_type" field.
func ContainerTypeIn(vs ...schema.ContainerType) predicate.ContainerCheck {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ContainerCheck(sql.FieldIn(FieldContainerType, v...))
}

// ContainerTypeNotIn applies the NotIn predicate on the "container_type" field.
func ContainerTypeNotIn(vs ...schema.ContainerType) predicate.ContainerCheck {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.ContainerCheck(sql.FieldNotIn(FieldContainerType, v...))
}

// ContainerIDEQ applies the EQ predicate on the "container_id" field.
func ContainerIDEQ(v int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldEQ(FieldContainerID, v))
}

// ContainerIDNEQ applies the NEQ predicate on the "container_id" field.
func ContainerIDNEQ(v int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldNEQ(FieldContainerID, v))
}

// ContainerIDIn applies the In predicate on the "container_id" field.
func ContainerIDIn(vs ...int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldIn(FieldContainerID, vs...))
}

// ContainerIDNotIn applies the NotIn predicate on the "container_id" field.
func ContainerIDNotIn(vs ...int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldNotIn(FieldContainerID, vs...))
}

// ContainerIDGT applies the GT predicate on the "container_id" field.
func ContainerIDGT(v int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldGT(FieldContainerID, v))
}

// ContainerIDGTE applies the GTE predicate on the "container_id" field.
func ContainerIDGTE(v int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldGTE(FieldContainerID, v))
}

// ContainerIDLT applies the LT predicate on the "container_id" field.
func ContainerIDLT(v int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldLT(FieldContainerID, v))
}

// ContainerIDLTE applies the LTE predicate on the "container_id" field.
func ContainerIDLTE(v int) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.FieldLTE(FieldContainerID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContainerCheck) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContainerCheck) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContainerCheck) predicate.ContainerCheck {
	return predicate.ContainerCheck(sql.NotPredicates(p))
}
